'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import DashboardNav from '@/components/DashboardNav'
import { createClient } from '@/lib/supabase/client'

type AccountState={email:string;displayName:string;twitchLogin:string;avatarUrl:string;internalEmail:boolean;emailConfirmed:boolean;createdAt:string;lastSignIn:string}

const internalEmail=(email:string)=>/^twitch-[^@]+@auth\.chromachat\.syntax-xxx\.is-a\.dev$/i.test(email)

export default function ProfilePage(){
  const supabase=useMemo(()=>createClient(),[]),router=useRouter()
  const[account,setAccount]=useState<AccountState|null>(null)
  const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('')
  const[status,setStatus]=useState('Loading account…'),[busy,setBusy]=useState(false)

  useEffect(()=>{void(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth');return}const{data:profile}=await supabase.from('profiles').select('display_name,twitch_login,avatar_url').eq('id',user.id).maybeSingle();const currentEmail=user.email||'',hidden=internalEmail(currentEmail);setAccount({email:hidden?'':currentEmail,displayName:String(profile?.display_name||user.user_metadata?.display_name||''),twitchLogin:String(profile?.twitch_login||user.user_metadata?.twitch_login||''),avatarUrl:String(profile?.avatar_url||user.user_metadata?.avatar_url||''),internalEmail:hidden,emailConfirmed:!!user.email_confirmed_at&&!hidden,createdAt:user.created_at||'',lastSignIn:user.last_sign_in_at||''});setEmail(hidden?'':currentEmail);setStatus(new URLSearchParams(window.location.search).get('email')==='confirmed'?'Email confirmed. You can now use email + password to sign in.':'Account ready')})()},[router,supabase])

  async function changeEmail(e:FormEvent){e.preventDefault();const next=email.trim().toLowerCase();if(!next){setStatus('Enter an email address');return}setBusy(true);setStatus('Sending verification email…');const{error}=await supabase.auth.updateUser({email:next},{emailRedirectTo:`${window.location.origin}/dashboard/profile?email=confirmed`});setBusy(false);if(error){setStatus(error.message);return}setStatus('Verification sent. Open the email from Supabase/CTCI to confirm the new login address.')}
  async function changePassword(e:FormEvent){e.preventDefault();if(password.length<12){setStatus('Use at least 12 characters for the password.');return}if(password!==confirm){setStatus('Passwords do not match.');return}setBusy(true);setStatus('Updating password…');const{error}=await supabase.auth.updateUser({password});setBusy(false);if(error){setStatus(error.message);return}setPassword('');setConfirm('');setStatus('Password updated. Manual email login is ready once your real email is confirmed.')}
  async function signOut(){await supabase.auth.signOut();router.replace('/')}

  if(!account)return <><DashboardNav onSignOut={signOut}/><main className="app-main"><section className="panel">{status}</section></main></>
  return <><DashboardNav onSignOut={signOut}/><main className="app-main">
    <section className="dashboard-hero"><div><span className="eyebrow">ACCOUNT</span><h1>Profile & sign-in</h1><p>Add a real email and password to your existing streamer account. Twitch remains linked, so both sign-in methods lead to the same CTCI dashboard.</p></div><div className="hero-status"><span className={`health-dot ${account.emailConfirmed?'online':''}`}/><div><strong>{account.emailConfirmed?'Manual login ready':account.internalEmail?'Twitch login only':'Email confirmation pending'}</strong><span>{status}</span></div></div></section>
    <div className="studio-layout"><section className="studio-content">
      <section className="panel"><div className="section-head"><div><span className="section-kicker">PROFILE</span><h2>Streamer identity</h2></div></div><div style={{display:'flex',gap:16,alignItems:'center'}}>{account.avatarUrl?<img src={account.avatarUrl} alt="" referrerPolicy="no-referrer" style={{width:68,height:68,borderRadius:16,objectFit:'cover'}}/>:<div className="brand-mark" style={{width:68,height:68}}>C</div>}<div><strong style={{fontSize:20}}>{account.displayName||account.twitchLogin||'Streamer'}</strong><div className="small muted">{account.twitchLogin?`Twitch: ${account.twitchLogin}`:'Twitch not linked'}</div></div></div></section>
      <section className="panel"><div className="section-head"><div><span className="section-kicker">EMAIL LOGIN</span><h2>Add or change email</h2><p className="muted">Your original internal Twitch auth address is never shown. A real email must be verified before it becomes your manual login.</p></div></div><form onSubmit={changeEmail}><div className="field"><label>Login email</label><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></div><div className="actions"><button className="btn primary" disabled={busy}>Send verification</button>{account.emailConfirmed&&<span className="status success">Verified</span>}</div></form></section>
      <section className="panel"><div className="section-head"><div><span className="section-kicker">PASSWORD</span><h2>Set manual-login password</h2><p className="muted">Passwords are handled only by Supabase Auth and are never written to CTCI application tables.</p></div></div><form onSubmit={changePassword}><div className="row"><div className="field"><label>New password</label><input type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} required/></div><div className="field"><label>Confirm password</label><input type="password" autoComplete="new-password" minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></div></div><button className="btn primary" disabled={busy}>Update password</button></form></section>
    </section><aside className="studio-sidebar"><section className="panel"><span className="section-kicker">LOGIN METHODS</span><h3>Connected methods</h3><div className="command-list"><div className="command-card"><strong>✓ Twitch OAuth</strong><div className="small muted">Primary streamer identity and channel connection.</div></div><div className="command-card"><strong>{account.emailConfirmed?'✓':'○'} Email + password</strong><div className="small muted">{account.emailConfirmed?account.email:'Add and verify a real email to enable it.'}</div></div></div></section><section className="panel"><h3>Security</h3><p className="small muted">Use a unique password. CTCI never displays or retrieves your existing password.</p>{account.lastSignIn&&<p className="small muted">Last sign-in: {new Date(account.lastSignIn).toLocaleString()}</p>}</section></aside></div>
  </main></>}
