import { NextRequest,NextResponse } from 'next/server'
import { createServerSupabase } from '@/lib/supabase/server'
import { createAdminSupabase } from '@/lib/supabase/admin'
import { builderCss,DEFAULT_CHAT_BUILDER,sanitizeBuilderCustomCss,sanitizeChatBuilder } from '@/lib/chat-builder'

export const runtime='nodejs'
export const dynamic='force-dynamic'
const BUCKET='ctci-chat-assets',MIME=new Set(['image/png','image/jpeg','image/webp','image/gif']),MAX=2*1024*1024
async function user(){const sb=await createServerSupabase();const{data:{user}}=await sb.auth.getUser();return user}

export async function GET(){const u=await user();if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const a=createAdminSupabase();const[overlay,assets,fonts]=await Promise.all([a.from('overlays').select('slug,builder_config,builder_custom_css').eq('user_id',u.id).single(),a.from('chat_builder_assets').select('id,label,storage_path,mime_type,size_bytes,created_at').eq('owner_id',u.id).order('created_at',{ascending:false}),a.from('font_assets').select('label').eq('owner_id',u.id).order('label')]);if(overlay.error)return NextResponse.json({error:'Overlay unavailable'},{status:404});const items=(assets.data||[]).map((x:any)=>({...x,url:a.storage.from(BUCKET).getPublicUrl(x.storage_path).data.publicUrl}));return NextResponse.json({slug:overlay.data.slug,config:sanitizeChatBuilder(overlay.data.builder_config||DEFAULT_CHAT_BUILDER),customCss:String(overlay.data.builder_custom_css||''),assets:items,fonts:(fonts.data||[]).map((x:any)=>String(x.label))},{headers:{'Cache-Control':'no-store'}})}

export async function PATCH(request:NextRequest){const u=await user();if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});try{const b=await request.json(),config=sanitizeChatBuilder(b.config),advanced=sanitizeBuilderCustomCss(b.customCss),a=createAdminSupabase(),css=[builderCss(config),advanced].filter(Boolean).join('\n\n');const r=await a.from('overlays').update({builder_config:config,builder_custom_css:advanced,custom_css:css,updated_at:new Date().toISOString()}).eq('user_id',u.id).select('slug').single();if(r.error)throw r.error;return NextResponse.json({ok:true,config,customCss:advanced,slug:r.data.slug})}catch(error:any){console.error('Chat builder save failed',error);const message=error instanceof Error?error.message:'Failed to save chat design';return NextResponse.json({error:message},{status:/not allowed|may only use|Do not include/i.test(message)?400:500})}}

export async function POST(request:NextRequest){const u=await user();if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});try{const form=await request.formData(),file=form.get('file');if(!(file instanceof File))return NextResponse.json({error:'Image file required'},{status:400});if(!MIME.has(file.type))return NextResponse.json({error:'Use PNG, JPG, WebP or GIF'},{status:400});if(file.size<1||file.size>MAX)return NextResponse.json({error:'Image must be 2 MB or smaller'},{status:400});const ext=file.type==='image/png'?'png':file.type==='image/jpeg'?'jpg':file.type==='image/webp'?'webp':'gif',path=`${u.id}/${crypto.randomUUID()}.${ext}`,a=createAdminSupabase(),bytes=new Uint8Array(await file.arrayBuffer()),upload=await a.storage.from(BUCKET).upload(path,bytes,{contentType:file.type,upsert:false,cacheControl:'31536000'});if(upload.error)throw upload.error;const label=String(form.get('label')||file.name||'Decoration').slice(0,80),row=await a.from('chat_builder_assets').insert({owner_id:u.id,label,storage_path:path,mime_type:file.type,size_bytes:file.size}).select('id,label,storage_path,mime_type,size_bytes,created_at').single();if(row.error){await a.storage.from(BUCKET).remove([path]);throw row.error}return NextResponse.json({asset:{...row.data,url:a.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}})}catch(error){console.error('Chat builder asset upload failed',error);return NextResponse.json({error:'Image upload failed'},{status:500})}}

export async function DELETE(request:NextRequest){const u=await user();if(!u)return NextResponse.json({error:'Unauthorized'},{status:401});const id=String(request.nextUrl.searchParams.get('id')||'');if(!id)return NextResponse.json({error:'Asset id required'},{status:400});const a=createAdminSupabase(),row=await a.from('chat_builder_assets').select('storage_path').eq('id',id).eq('owner_id',u.id).maybeSingle();if(row.error)return NextResponse.json({error:'Asset lookup failed'},{status:500});if(!row.data)return NextResponse.json({error:'Asset not found'},{status:404});const del=await a.storage.from(BUCKET).remove([row.data.storage_path]);if(del.error)return NextResponse.json({error:'Asset delete failed'},{status:500});const db=await a.from('chat_builder_assets').delete().eq('id',id).eq('owner_id',u.id);if(db.error)return NextResponse.json({error:'Asset delete failed'},{status:500});return NextResponse.json({ok:true})}