'use client'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import DashboardNav from '@/components/DashboardNav'
import { createClient } from '@/lib/supabase/client'
type Msg={id:string;source:string;event_type:string;chatter_name:string;chatter_login:string;message_text:string;created_at:string;event_data:any}
export default function Studio(){const router=useRouter(),[messages,setMessages]=useState<Msg[]>([]),[filter,setFilter]=useState<'all'|'twitch'|'youtube'>('all'),[status,setStatus]=useState('Connecting to live chat…')
useEffect(()=>{let alive=true,timer:number|undefined;async function load(){const r=await fetch('/api/studio/messages',{cache:'no-store'}),b=await r.json().catch(()=>({}));if(alive&&r.ok){setMessages(b.messages||[]);setStatus('Live chat connected')}else if(alive)setStatus(b.error||'Could not load chat');if(alive)timer=window.setTimeout(load,2500)}void load();return()=>{alive=false;if(timer)clearTimeout(timer)}},[])
async function remove(id:string){const r=await fetch(`/api/studio/messages?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(r.ok)setMessages(v=>v.filter(x=>x.id!==id));else setStatus('Could not hide message')}
async function signOut(){const sb=createClient();await sb.auth.signOut();router.replace('/')}
const visible=messages.filter(m=>filter==='all'||m.source===filter)
return <><DashboardNav onSignOut={signOut}/><main className="app-main"><section className="dashboard-hero"><div><span className="eyebrow">LIVE CHAT STUDIO</span><h1>Run Twitch and YouTube chat from one screen.</h1><p>Watch the merged feed during stream, filter by platform, spot paid/member events, and remove messages from the active overlay.</p></div><div className="hero-status"><span className="health-dot online"/><div><strong>{visible.length} recent messages</strong><span>{status}</span></div></div></section><section className="panel"><div className="section-head"><div><span className="section-kicker">LIVE FEED</span><h2>Merged chat</h2></div><div className="actions"><button className={`btn compact ${filter==='all'?'primary':''}`} onClick={()=>setFilter('all')}>Both</button><button className={`btn compact ${filter==='twitch'?'primary':''}`} onClick={()=>setFilter('twitch')}>Twitch</button><button className={`btn compact ${filter==='youtube'?'primary':''}`} onClick={()=>setFilter('youtube')}>YouTube</button></div></div><div style={{display:'grid',gap:8}}>{visible.map(m=><article className="setup-card" key={m.id}><div className="setup-index" style={{background:m.source==='youtube'?'#ff0033':'#9147ff',color:'#fff'}}>{m.source==='youtube'?'▶':'T'}</div><div className="setup-copy"><h3>{m.chatter_name}</h3><p>{m.message_text}</p><span className="small muted">{m.event_type!=='message'?`${m.event_type.replaceAll('_',' ')} · `:''}{new Date(m.created_at).toLocaleTimeString()}</span></div><button className="btn compact ghost" onClick={()=>remove(m.id)}>Hide</button></article>)}</div></section></main></>}
