'use client'
import { useEffect,useState } from 'react'
import { DEFAULT_CHAT_BUILDER,type BuilderSymbol,type ChatBuilderConfig } from '@/lib/chat-builder'
type Asset={id:string;label:string;url:string}
const presets:Record<string,Partial<ChatBuilderConfig>>={Reference:{enabled:true,layout:{mode:'stacked',align:'left',gap:7,maxWidth:520},username:{...DEFAULT_CHAT_BUILDER.username,background:'#B755F2',radius:7,fontSize:18},message:{...DEFAULT_CHAT_BUILDER.message,background:'#292936',opacity:.72,radius:7,fontSize:18}},Clean:{enabled:true,username:{...DEFAULT_CHAT_BUILDER.username,mode:'plain',opacity:0},message:{...DEFAULT_CHAT_BUILDER.message,background:'#0A0A0A',opacity:.55,shadow:'none'}},Neon:{enabled:true,username:{...DEFAULT_CHAT_BUILDER.username,background:'#8B5CF6',radius:14},message:{...DEFAULT_CHAT_BUILDER.message,background:'#090512',opacity:.82,borderWidth:1,borderColor:'#8B5CF6',radius:14,shadow:'strong'}}}
export default function ChatBuilderEditor(){const[cfg,setCfg]=useState(DEFAULT_CHAT_BUILDER),[assets,setAssets]=useState<Asset[]>([]),[slug,setSlug]=useState(''),[status,setStatus]=useState('Loading…'),[busy,setBusy]=useState(false)
useEffect(()=>{void fetch('/api/overlay/builder',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setCfg(b.config);setAssets(b.assets||[]);setSlug(b.slug||'');setStatus('Ready — preview is local until Save.')}).catch(e=>setStatus(e.message))},[])
const set=(path:string,value:any)=>setCfg(c=>{const n=structuredClone(c) as any,p=path.split('.');let x=n;for(let i=0;i<p.length-1;i++)x=x[p[i]];x[p[p.length-1]]=value;return n})
async function save(){setBusy(true);setStatus('Saving…');try{const r=await fetch('/api/overlay/builder',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({config:cfg})}),b=await r.json();if(!r.ok)throw new Error(b.error);setCfg(b.config);setStatus('Saved — OBS updates through Realtime.')}catch(e:any){setStatus(e.message||'Save failed')}finally{setBusy(false)}}
async function upload(file:File){const f=new FormData();f.set('file',file);f.set('label',file.name);setStatus('Uploading…');const r=await fetch('/api/overlay/builder',{method:'POST',body:f}),b=await r.json();if(!r.ok){setStatus(b.error||'Upload failed');return}setAssets(a=>[b.asset,...a]);setStatus('Uploaded. Click the image to add it as a symbol.')}
function symbol(type:'text'|'image',value:string){const s:BuilderSymbol={id:crypto.randomUUID(),type,value,position:'username_after',size:20,gap:4};setCfg(c=>({...c,symbols:[...c.symbols,s].slice(0,4)}))}
return <div style={{display:'grid',gridTemplateColumns:'minmax(330px,430px) minmax(420px,1fr)',gap:18,alignItems:'start'}}><section className="panel" style={{maxHeight:'calc(100vh - 120px)',overflow:'auto'}}><div className="section-head"><div><h2>Controls</h2><p className="muted">{status}</p></div></div><div className="actions" style={{flexWrap:'wrap'}}>{Object.entries(presets).map(([n,p])=><button key={n} className="btn compact" onClick={()=>setCfg({...structuredClone(DEFAULT_CHAT_BUILDER),...structuredClone(p)} as ChatBuilderConfig)}>{n}</button>)}<label className="check"><input type="checkbox" checked={cfg.enabled} onChange={e=>set('enabled',e.target.checked)}/> Enabled</label></div>
<Group title="Layout"><Sel label="Mode" v={cfg.layout.mode} values={['stacked','compact']} set={v=>set('layout.mode',v)}/><Sel label="Align" v={cfg.layout.align} values={['left','center','right']} set={v=>set('layout.align',v)}/><Num label="Gap" v={cfg.layout.gap} min={0} max={64} set={v=>set('layout.gap',v)}/><Num label="Max width" v={cfg.layout.maxWidth} min={180} max={1920} set={v=>set('layout.maxWidth',v)}/></Group>
<Group title="Username"><Sel label="Style" v={cfg.username.mode} values={['chip','plain']} set={v=>set('username.mode',v)}/><Clr label="Chip" v={cfg.username.background} set={v=>set('username.background',v)}/><Clr label="Text" v={cfg.username.textColor} set={v=>set('username.textColor',v)}/><Num label="Opacity" v={cfg.username.opacity} min={0} max={1} step={.05} set={v=>set('username.opacity',v)}/><Num label="Radius" v={cfg.username.radius} min={0} max={64} set={v=>set('username.radius',v)}/><Num label="Size" v={cfg.username.fontSize} min={8} max={96} set={v=>set('username.fontSize',v)}/><Txt label="Prefix" v={cfg.username.prefix} set={v=>set('username.prefix',v)}/><Txt label="Suffix" v={cfg.username.suffix} set={v=>set('username.suffix',v)}/><Check label="Platform icon" v={cfg.username.showPlatformIcon} set={v=>set('username.showPlatformIcon',v)}/><Check label="Badges" v={cfg.username.showBadges} set={v=>set('username.showBadges',v)}/></Group>
<Group title="Message"><Clr label="Bubble" v={cfg.message.background} set={v=>set('message.background',v)}/><Clr label="Text" v={cfg.message.textColor} set={v=>set('message.textColor',v)}/><Num label="Opacity" v={cfg.message.opacity} min={0} max={1} step={.05} set={v=>set('message.opacity',v)}/><Num label="Blur" v={cfg.message.blur} min={0} max={40} set={v=>set('message.blur',v)}/><Num label="Radius" v={cfg.message.radius} min={0} max={64} set={v=>set('message.radius',v)}/><Num label="Font size" v={cfg.message.fontSize} min={8} max={128} set={v=>set('message.fontSize',v)}/><Num label="Border" v={cfg.message.borderWidth} min={0} max={8} set={v=>set('message.borderWidth',v)}/><Sel label="Shadow" v={cfg.message.shadow} values={['none','soft','strong']} set={v=>set('message.shadow',v)}/></Group>
<Group title="Symbols"><button className="btn compact" onClick={()=>symbol('text','♡')}>+ Text symbol</button><label className="btn compact">Upload image<input hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label>{assets.slice(0,6).map(a=><button key={a.id} className="btn compact ghost" onClick={()=>symbol('image',a.url)}><img src={a.url} alt="" style={{width:20,height:20,objectFit:'contain'}}/> Add</button>)}{cfg.symbols.map(s=><div key={s.id} className="field"><label>{s.type==='image'?'Image':s.value}</label><select value={s.position} onChange={e=>setCfg(c=>({...c,symbols:c.symbols.map(x=>x.id===s.id?{...x,position:e.target.value as any}:x)}))}>{['row_before','username_before','username_after','row_after'].map(v=><option key={v}>{v}</option>)}</select><button className="btn compact ghost" onClick={()=>setCfg(c=>({...c,symbols:c.symbols.filter(x=>x.id!==s.id)}))}>Remove</button></div>)}</Group>
<div className="actions" style={{position:'sticky',bottom:0,paddingTop:12}}><button className="btn primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save to OBS'}</button>{slug&&<a className="btn" href={`/overlay/${slug}`} target="_blank" rel="noreferrer">Open overlay</a>}</div></section><section className="panel" style={{position:'sticky',top:84}}><div className="section-head"><div><h2>Live preview</h2><p className="muted">Reference preset matches the purple username-chip + translucent bubble look from your image.</p></div></div><Preview c={cfg}/></section></div>}
function Preview({c}:{c:ChatBuilderConfig}){const rows=[['Spiky7489','this chat can be styled per streamer'],['Cody0ELF','custom symbols and badges ✨'],['Drachengott0815','Denke ich auch, hab gleich wieder 20 memes auf vorrat']];return <div style={{height:520,padding:28,borderRadius:18,background:'linear-gradient(145deg,#dce9d1,#a8c2ad 45%,#d8d6bc)',display:'flex',flexDirection:'column',justifyContent:'center',gap:c.layout.gap,alignItems:c.layout.align==='center'?'center':c.layout.align==='right'?'flex-end':'flex-start',overflow:'hidden'}}>{rows.map(([name,msg])=><div key={name} style={{width:`min(100%,${c.layout.maxWidth}px)`}}><div style={{display:'flex',alignItems:'center',gap:6}}>{c.username.showPlatformIcon&&<span>▣</span>}<strong style={{background:c.username.mode==='chip'?alpha(c.username.background,c.username.opacity):'transparent',color:c.username.textColor,borderRadius:c.username.radius,padding:c.username.mode==='chip'?`${c.username.paddingY}px ${c.username.paddingX}px`:0,fontSize:c.username.fontSize}}>{c.username.prefix}{name}{c.username.suffix}</strong>{c.username.showBadges&&<span style={{marginLeft:'auto'}}>♙ ♙ ♙</span>}</div><div style={{marginTop:c.layout.mode==='stacked'?c.username.gap:0,background:alpha(c.message.background,c.message.opacity),color:c.message.textColor,borderRadius:c.message.radius,padding:`${c.message.paddingY}px ${c.message.paddingX}px`,fontSize:c.message.fontSize,backdropFilter:`blur(${c.message.blur}px)`,border:`${c.message.borderWidth}px solid ${c.message.borderColor}`}}>{msg}</div></div>)}</div>}
const alpha=(h:string,a:number)=>{const n=parseInt(h.slice(1),16);return`rgba(${n>>16},${n>>8&255},${n&255},${a})`}
function Group({title,children}:{title:string;children:any}){return <fieldset style={{border:0,padding:0,margin:'20px 0 0'}}><legend style={{fontWeight:800,marginBottom:8}}>{title}</legend><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9}}>{children}</div></fieldset>}
function Num({label,v,set,min,max,step=1}:{label:string;v:number;set:(v:number)=>void;min:number;max:number;step?:number}){return <div className="field"><label>{label}</label><input type="number" value={v} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/></div>}
function Clr({label,v,set}:{label:string;v:string;set:(v:string)=>void}){return <div className="field"><label>{label}</label><input type="color" value={v} onChange={e=>set(e.target.value)}/></div>}
function Txt({label,v,set}:{label:string;v:string;set:(v:string)=>void}){return <div className="field"><label>{label}</label><input value={v} maxLength={12} onChange={e=>set(e.target.value)}/></div>}
function Sel({label,v,values,set}:{label:string;v:string;values:string[];set:(v:string)=>void}){return <div className="field"><label>{label}</label><select value={v} onChange={e=>set(e.target.value)}>{values.map(x=><option key={x}>{x}</option>)}</select></div>}
function Check({label,v,set}:{label:string;v:boolean;set:(v:boolean)=>void}){return <label className="check"><input type="checkbox" checked={v} onChange={e=>set(e.target.checked)}/>{label}</label>}
