export type BuilderSymbol={id:string;type:'text'|'image';value:string;position:'row_before'|'username_before'|'username_after'|'row_after';size:number;gap:number}
export type ChatBuilderConfig={version:1;enabled:boolean;layout:{mode:'stacked'|'compact';align:'left'|'center'|'right';gap:number;maxWidth:number};username:{mode:'chip'|'plain';background:string;textColor:string;opacity:number;radius:number;paddingX:number;paddingY:number;gap:number;showPlatformIcon:boolean;showBadges:boolean;prefix:string;suffix:string;fontSize:number;fontWeight:number};message:{background:string;textColor:string;opacity:number;radius:number;paddingX:number;paddingY:number;blur:number;borderWidth:number;borderColor:string;shadow:'none'|'soft'|'strong';fontSize:number;lineHeight:number};badges:{size:number;gap:number;placement:'right'|'before_username'|'hidden'};symbols:BuilderSymbol[]}

export const DEFAULT_CHAT_BUILDER:ChatBuilderConfig={version:1,enabled:false,layout:{mode:'stacked',align:'left',gap:8,maxWidth:760},username:{mode:'chip',background:'#9147FF',textColor:'#FFFFFF',opacity:1,radius:8,paddingX:10,paddingY:5,gap:6,showPlatformIcon:true,showBadges:true,prefix:'',suffix:'',fontSize:20,fontWeight:700},message:{background:'#15151F',textColor:'#FFFFFF',opacity:.78,radius:8,paddingX:10,paddingY:7,blur:8,borderWidth:0,borderColor:'#FFFFFF',shadow:'soft',fontSize:24,lineHeight:1.3},badges:{size:18,gap:4,placement:'right'},symbols:[]}

const num=(v:any,min:number,max:number,fallback:number)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback}
const color=(v:any,fallback:string)=>/^#[0-9a-f]{6}$/i.test(String(v||''))?String(v).toUpperCase():fallback
const text=(v:any,max=32)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,'').slice(0,max)
const choice=<T extends string>(v:any,allowed:T[],fallback:T)=>allowed.includes(v as T)?v as T:fallback

export function sanitizeChatBuilder(raw:any):ChatBuilderConfig{
  const d=DEFAULT_CHAT_BUILDER,r=raw&&typeof raw==='object'?raw:{},l=r.layout||{},u=r.username||{},m=r.message||{},b=r.badges||{}
  const symbols=(Array.isArray(r.symbols)?r.symbols:[]).slice(0,4).map((s:any,index:number):BuilderSymbol=>({
    id:text(s?.id||`symbol-${index}`,40),type:s?.type==='image'?'image':'text',value:text(s?.value,s?.type==='image'?500:12),position:choice(s?.position,['row_before','username_before','username_after','row_after'] as const,'username_after'),size:num(s?.size,8,96,20),gap:num(s?.gap,0,40,4)
  })).filter((s:BuilderSymbol)=>s.value)
  return{version:1,enabled:r.enabled===true,layout:{mode:choice(l.mode,['stacked','compact'],'stacked'),align:choice(l.align,['left','center','right'],'left'),gap:num(l.gap,0,64,d.layout.gap),maxWidth:num(l.maxWidth,180,1920,d.layout.maxWidth)},username:{mode:choice(u.mode,['chip','plain'],'chip'),background:color(u.background,d.username.background),textColor:color(u.textColor,d.username.textColor),opacity:num(u.opacity,0,1,d.username.opacity),radius:num(u.radius,0,64,d.username.radius),paddingX:num(u.paddingX,0,40,d.username.paddingX),paddingY:num(u.paddingY,0,24,d.username.paddingY),gap:num(u.gap,0,32,d.username.gap),showPlatformIcon:u.showPlatformIcon!==false,showBadges:u.showBadges!==false,prefix:text(u.prefix,12),suffix:text(u.suffix,12),fontSize:num(u.fontSize,8,96,d.username.fontSize),fontWeight:num(u.fontWeight,100,900,d.username.fontWeight)},message:{background:color(m.background,d.message.background),textColor:color(m.textColor,d.message.textColor),opacity:num(m.opacity,0,1,d.message.opacity),radius:num(m.radius,0,64,d.message.radius),paddingX:num(m.paddingX,0,64,d.message.paddingX),paddingY:num(m.paddingY,0,48,d.message.paddingY),blur:num(m.blur,0,40,d.message.blur),borderWidth:num(m.borderWidth,0,8,d.message.borderWidth),borderColor:color(m.borderColor,d.message.borderColor),shadow:choice(m.shadow,['none','soft','strong'],'soft'),fontSize:num(m.fontSize,8,128,d.message.fontSize),lineHeight:num(m.lineHeight,1,2,d.message.lineHeight)},badges:{size:num(b.size,8,64,d.badges.size),gap:num(b.gap,0,24,d.badges.gap),placement:choice(b.placement,['right','before_username','hidden'],'right')},symbols}
}

function rgba(hex:string,opacity:number){const h=hex.replace('#','');return`rgba(${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)},${opacity})`}
function escContent(value:string){return JSON.stringify(value)}
function symbolRule(symbol:BuilderSymbol){const selector=symbol.position==='row_before'?'.chat-message::before':symbol.position==='row_after'?'.chat-message::after':symbol.position==='username_before'?'.chat-message strong::before':'.chat-message strong::after';if(symbol.type==='image'){const safe=/^https:\/\/[a-z0-9.-]+\/storage\/v1\/object\/public\/ctci-chat-assets\//i.test(symbol.value)?symbol.value:'';if(!safe)return'';return`${selector}{content:""!important;display:inline-block!important;width:${symbol.size}px!important;height:${symbol.size}px!important;background:url(${JSON.stringify(safe)}) center/contain no-repeat!important;vertical-align:middle!important;margin:${symbol.position==='row_before'||symbol.position==='row_after'?symbol.gap:0}px ${symbol.gap}px!important;}`}
return`${selector}{content:${escContent(symbol.value)}!important;display:inline-block!important;font-size:${symbol.size}px!important;line-height:1!important;vertical-align:middle!important;margin:${symbol.position==='row_before'||symbol.position==='row_after'?symbol.gap:0}px ${symbol.gap}px!important;}`}

export function builderCss(config:ChatBuilderConfig){if(!config.enabled)return'';const c=config,align=c.layout.align==='center'?'auto':c.layout.align==='right'?'0 0 0 auto':'0 auto 0 0',shadow=c.message.shadow==='strong'?'0 14px 42px rgba(0,0,0,.48)':c.message.shadow==='soft'?'0 6px 24px rgba(0,0,0,.25)':'none',stacked=c.layout.mode==='stacked';return`/* CTCI visual chat builder v1 */
.overlay-root .chat-message{position:relative!important;width:min(100%,${c.layout.maxWidth}px)!important;margin:${c.layout.gap}px ${align}!important;padding:${c.message.paddingY}px ${c.message.paddingX}px!important;background:${rgba(c.message.background,c.message.opacity)}!important;color:${c.message.textColor}!important;border:${c.message.borderWidth}px solid ${c.message.borderColor}!important;border-radius:${c.message.radius}px!important;box-shadow:${shadow}!important;backdrop-filter:blur(${c.message.blur}px)!important;-webkit-backdrop-filter:blur(${c.message.blur}px)!important;font-size:${c.message.fontSize}px!important;line-height:${c.message.lineHeight}!important;overflow:visible!important;}
.overlay-root .chat-message strong{${stacked?'display:block':'display:inline-flex'}!important;width:max-content!important;max-width:calc(100% - 28px)!important;margin:${stacked?`-${c.message.paddingY+2}px 0 ${c.username.gap}px ${c.username.showPlatformIcon?'22px':'0'}`:'0 .35em 0 0'}!important;padding:${c.username.mode==='chip'?`${c.username.paddingY}px ${c.username.paddingX}px`:'0'}!important;background:${c.username.mode==='chip'?rgba(c.username.background,c.username.opacity):'transparent'}!important;color:${c.username.textColor}!important;border-radius:${c.username.radius}px!important;font-size:${c.username.fontSize}px!important;font-weight:${c.username.fontWeight}!important;line-height:1.1!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;}
.overlay-root .platform-icon{${c.username.showPlatformIcon?'':'display:none!important;'}${stacked&&c.username.showPlatformIcon?'position:absolute!important;left:'+c.message.paddingX+'px!important;top:'+Math.max(2,c.username.paddingY)+'px!important;':''}width:${Math.max(12,c.username.fontSize-2)}px!important;height:${Math.max(12,c.username.fontSize-2)}px!important;}
.overlay-root .custom-badge{${!c.username.showBadges||c.badges.placement==='hidden'?'display:none!important;':c.badges.placement==='right'?'float:right!important;':''}font-size:${c.badges.size}px!important;margin-left:${c.badges.gap}px!important;max-width:none!important;}
.overlay-root .custom-badge img{width:${c.badges.size}px!important;height:${c.badges.size}px!important;max-width:${c.badges.size}px!important;max-height:${c.badges.size}px!important;}
${c.username.prefix?`.overlay-root .chat-message strong::before{content:${escContent(c.username.prefix+' ')};}`:''}
${c.username.suffix?`.overlay-root .chat-message strong::after{content:${escContent(' '+c.username.suffix)};}`:''}
${c.symbols.map(symbolRule).join('\n')}`}
