import type { SupabaseClient } from '@supabase/supabase-js'

export type CommandPermission='broadcaster'|'moderator'|'vip'|'subscriber'|'viewer'
export type ParsedCommand={prefix:string;command:string;args:string[];rawArgs:string;raw:string}
export type CommandActor={twitchUserId:string;login:string;roles:Set<CommandPermission>}
export type CommandContext={admin:SupabaseClient;ownerId:string;channelTwitchUserId:string;actor:CommandActor;parsed:ParsedCommand}
export type ChatCommand={name:string;aliases?:string[];description:string;source:'core'|'plugin';pluginId?:string;permissions:CommandPermission[];cooldown?:{globalSeconds?:number;userSeconds?:number};handler:(ctx:CommandContext)=>Promise<{message?:string;changed?:Record<string,unknown>}>}
const registry=new Map<string,ChatCommand>()
export function registerCommand(c:ChatCommand){for(const k of [c.name,...(c.aliases||[])].map(x=>x.toLowerCase())){const e=registry.get(k);if(e&&e.source==='core'&&c.source==='plugin')throw new Error(`Plugin command cannot override built-in command: ${k}`)};[c.name,...(c.aliases||[])].forEach(k=>registry.set(k.toLowerCase(),c))}
export function unregisterPluginCommands(id:string){for(const [k,v] of registry)if(v.source==='plugin'&&v.pluginId===id)registry.delete(k)}
export function listCommands(){return [...new Map([...registry.values()].map(c=>[c.name,c])).values()]}
export function parseCommand(message:string,prefix:string):ParsedCommand|null{if(!message.toLowerCase().startsWith(prefix.toLowerCase()))return null;const body=message.slice(prefix.length).trim();if(!body||body.length>500)return null;const t=tokenize(body);if(!t.length)return null;const [command,...args]=t;return{prefix,command:command.toLowerCase(),args,rawArgs:body.slice(command.length).trim(),raw:message}}
function tokenize(s:string){const o:string[]=[];let c='',q:'"'|"'"|null=null,e=false;for(const ch of s){if(e){c+=ch;e=false;continue}if(ch==='\\'){e=true;continue}if(q){if(ch===q)q=null;else c+=ch;continue}if(ch==='"'||ch==="'"){q=ch;continue}if(/\s/.test(ch)){if(c){o.push(c);c=''}continue}c+=ch}if(q)throw new Error('Unclosed quoted argument');if(c)o.push(c);return o}

export async function executeCommand(ctx:CommandContext){let command=registry.get(ctx.parsed.command),config:any=null;if(command){config=(await ctx.admin.from('command_configurations').select('*').eq('owner_id',ctx.ownerId).eq('command_name',command.name).maybeSingle()).data}else{config=(await ctx.admin.from('command_configurations').select('*').eq('owner_id',ctx.ownerId).contains('aliases',[ctx.parsed.command]).maybeSingle()).data;if(config)command=registry.get(String(config.command_name).toLowerCase())}if(!command)return{handled:false as const};if(config?.enabled===false)return audit(ctx,command,false,'disabled');const allowed=(config?.permissions?.length?config.permissions:command.permissions) as CommandPermission[];if(!allowed.some(r=>ctx.actor.roles.has(r)))return audit(ctx,command,false,'forbidden');const {data:ok,error}=await ctx.admin.rpc('try_command_cooldown',{p_owner_id:ctx.ownerId,p_command_name:command.name,p_twitch_user_id:ctx.actor.twitchUserId,p_global_seconds:config?.global_cooldown_seconds??command.cooldown?.globalSeconds??1,p_user_seconds:config?.user_cooldown_seconds??command.cooldown?.userSeconds??5});if(error)throw error;if(!ok)return audit(ctx,command,false,'cooldown');try{const result=await command.handler(ctx);if(config)await ctx.admin.from('command_configurations').update({usage_count:Number(config.usage_count||0)+1,last_used_at:new Date().toISOString()}).eq('id',config.id);else await ctx.admin.from('command_configurations').insert({owner_id:ctx.ownerId,command_name:command.name,aliases:command.aliases||[],permissions:command.permissions,source:command.source,plugin_id:command.pluginId||null,usage_count:1,last_used_at:new Date().toISOString()});await audit(ctx,command,true,null);return{handled:true as const,success:true,...result}}catch(err){await audit(ctx,command,false,err instanceof Error?err.message.slice(0,80):'handler_error');return{handled:true as const,success:false}}}
async function audit(ctx:CommandContext,c:ChatCommand,success:boolean,error_code:string|null){await ctx.admin.from('command_audit_log').insert({owner_id:ctx.ownerId,channel_twitch_user_id:ctx.channelTwitchUserId,twitch_user_id:ctx.actor.twitchUserId,twitch_login:ctx.actor.login,command_name:c.name,raw_command:ctx.parsed.raw.slice(0,500),sanitized_args:ctx.parsed.args.slice(0,20),source:c.source,plugin_id:c.pluginId||null,success,error_code});return{handled:true as const,success}}
const color=(v:string)=>{if(v==='transparent')return v;if(!/^#[0-9a-f]{6}$/i.test(v))throw new Error('invalid_color');return v}
const integer=(v:string,min:number,max:number,code:string)=>{const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw new Error(code);return n}
const bool=(v:string)=>{if(['on','true','1','yes'].includes(v))return true;if(['off','false','0','no'].includes(v))return false;throw new Error('invalid_boolean')}
async function overlay(ctx:CommandContext,patch:Record<string,unknown>){const{error}=await ctx.admin.from('overlays').update(patch).eq('user_id',ctx.ownerId);if(error)throw error;return{changed:patch}}
async function rolePatch(ctx:CommandContext,role:string,patch:Record<string,unknown>){if(!['viewer','subscriber','vip','moderator','broadcaster','founder'].includes(role))throw new Error('invalid_role');const r=await ctx.admin.from('overlays').select('role_styles').eq('user_id',ctx.ownerId).single();if(r.error)throw r.error;const styles={...(r.data?.role_styles||{})};styles[role]={...(styles[role]||{}),...patch};return overlay(ctx,{role_styles:styles})}
async function targetStyle(ctx:CommandContext,login:string,patch:Record<string,unknown>){login=login.toLowerCase();if(!/^[a-z0-9_]{3,25}$/.test(login))throw new Error('invalid_user');const ev=await ctx.admin.from('chat_events').select('chatter_user_id').eq('broadcaster_user_id',ctx.channelTwitchUserId).eq('chatter_login',login).order('created_at',{ascending:false}).limit(1).maybeSingle();const payload={owner_id:ctx.ownerId,chatter_login:login,twitch_user_id:ev.data?.chatter_user_id||null,...patch};const{error}=await ctx.admin.from('chatter_styles').upsert(payload,{onConflict:'owner_id,chatter_login'});if(error)throw error;return{changed:patch}}

const B=['broadcaster'] as CommandPermission[], BM=['broadcaster','moderator'] as CommandPermission[], ALL=['viewer','subscriber','vip','moderator','broadcaster'] as CommandPermission[]
registerCommand({name:'font',description:'Change message font',source:'core',permissions:B,handler:c=>{const v=c.parsed.rawArgs.trim();if(!v||v.length>80)throw new Error('invalid_font');return overlay(c,{font_family:v})}})
registerCommand({name:'namefont',description:'Change username font',source:'core',permissions:B,handler:c=>{const v=c.parsed.rawArgs.trim();if(!v||v.length>80)throw new Error('invalid_font');return overlay(c,{username_font_family:v})}})
registerCommand({name:'fontsize',aliases:['fs'],description:'Change message font size',source:'core',permissions:B,handler:c=>overlay(c,{font_size:integer(c.parsed.args[0],10,96,'invalid_size')})})
registerCommand({name:'namesize',description:'Change username size',source:'core',permissions:B,handler:c=>overlay(c,{username_font_size:integer(c.parsed.args[0],10,96,'invalid_size')})})
registerCommand({name:'color',aliases:['colour'],description:'Change message color',source:'core',permissions:BM,handler:c=>overlay(c,{message_color:color((c.parsed.args[0]||'').toLowerCase())})})
registerCommand({name:'namecolor',description:'Change username color',source:'core',permissions:B,handler:c=>overlay(c,{username_color:color((c.parsed.args[0]||'').toLowerCase())})})
registerCommand({name:'background',aliases:['bg'],description:'Change overlay background',source:'core',permissions:B,handler:c=>{const v=color((c.parsed.args[0]||'').toLowerCase());return overlay(c,v==='transparent'?{background_opacity:0}:{background_color:v,background_opacity:1})}})
registerCommand({name:'opacity',description:'Change overlay opacity',source:'core',permissions:B,handler:c=>{const n=Number(c.parsed.args[0]);if(!Number.isFinite(n)||n<0||n>1)throw new Error('invalid_opacity');return overlay(c,{background_opacity:n})}})
registerCommand({name:'rainbow',description:'Rainbow usernames/messages',source:'core',permissions:B,handler:c=>{const v=(c.parsed.args[0]||'').toLowerCase();const mode=v==='on'?'all':v==='off'?'off':v;if(!['off','usernames','messages','all'].includes(mode))throw new Error('invalid_rainbow');return overlay(c,{rainbow_mode:mode})}})
registerCommand({name:'glow',description:'Enable or color glow',source:'core',permissions:B,handler:c=>{const v=(c.parsed.args[0]||'').toLowerCase();if(v.startsWith('#'))return overlay(c,{glow_enabled:true,glow_color:color(v)});return overlay(c,{glow_enabled:bool(v)})}})
registerCommand({name:'animation',aliases:['anim'],description:'Change chat animation',source:'core',permissions:B,handler:c=>{const v=(c.parsed.args[0]||'').toLowerCase();if(!['fade','slide','pop','bounce','none'].includes(v))throw new Error('invalid_animation');return overlay(c,{animation:v})}})
registerCommand({name:'theme',description:'Apply theme preset',source:'core',permissions:B,handler:c=>{const v=(c.parsed.args[0]||'').toLowerCase();const themes:any={minimal:{theme:'minimal',font_family:'Inter',background_opacity:0,bubble_opacity:.55,border_radius:8,rainbow_mode:'off',glow_enabled:false},neon:{theme:'neon',message_color:'#F8F7FF',username_color:'#C084FC',background_color:'#08050F',background_opacity:.72,bubble_color:'#151020',glow_enabled:true,glow_color:'#A855F7'},retro:{theme:'retro',font_family:'monospace',message_color:'#FDE68A',username_color:'#FB923C',background_color:'#1C1208',background_opacity:.8,bubble_color:'#2B1B0E',glow_enabled:false},cyberpunk:{theme:'cyberpunk',message_color:'#F9FAFB',username_color:'#00FFFF',background_color:'#070713',background_opacity:.78,bubble_color:'#15152A',glow_enabled:true,glow_color:'#FF00AA'}};if(!themes[v])throw new Error('invalid_theme');return overlay(c,themes[v])}})
registerCommand({name:'density',description:'Change chat density',source:'core',permissions:B,handler:c=>{const v=(c.parsed.args[0]||'').toLowerCase();const p:any={compact:{density:'compact',message_spacing:3},normal:{density:'normal',message_spacing:10},comfortable:{density:'comfortable',message_spacing:16},large:{density:'large',message_spacing:22}};if(!p[v])throw new Error('invalid_density');return overlay(c,p[v])}})
registerCommand({name:'lifetime',description:'Change message lifetime',source:'core',permissions:B,handler:c=>{const v=(c.parsed.args[0]||'').toLowerCase();return overlay(c,{fade_seconds:v==='off'?0:integer(v,0,300,'invalid_lifetime')})}})
registerCommand({name:'maxmessages',description:'Change maximum messages',source:'core',permissions:B,handler:c=>overlay(c,{max_messages:integer(c.parsed.args[0],1,100,'invalid_maxmessages')})})
registerCommand({name:'userfont',description:'Set a viewer font',source:'core',permissions:B,handler:c=>{const [u,...f]=c.parsed.args;if(!u||!f.length)throw new Error('missing_args');return targetStyle(c,u,{font_family:f.join(' ')})}})
registerCommand({name:'usercolor',description:'Set a viewer color',source:'core',permissions:B,handler:c=>targetStyle(c,c.parsed.args[0]||'',{message_color:color((c.parsed.args[1]||'').toLowerCase())})})
registerCommand({name:'userglow',description:'Set a viewer glow',source:'core',permissions:B,handler:c=>targetStyle(c,c.parsed.args[0]||'',{glow_color:color((c.parsed.args[1]||'').toLowerCase())})})
registerCommand({name:'userreset',description:'Reset viewer style',source:'core',permissions:B,handler:async c=>{const u=(c.parsed.args[0]||'').toLowerCase();const{error}=await c.admin.from('chatter_styles').delete().eq('owner_id',c.ownerId).eq('chatter_login',u);if(error)throw error;return{changed:{user:u}}}})
registerCommand({name:'rolefont',description:'Set role font',source:'core',permissions:B,handler:c=>rolePatch(c,(c.parsed.args[0]||'').toLowerCase(),{font_family:c.parsed.args.slice(1).join(' ')})})
registerCommand({name:'rolecolor',description:'Set role color',source:'core',permissions:B,handler:c=>rolePatch(c,(c.parsed.args[0]||'').toLowerCase(),{message_color:color((c.parsed.args[1]||'').toLowerCase())})})
registerCommand({name:'roleglow',description:'Set role glow',source:'core',permissions:B,handler:c=>{const v=(c.parsed.args[1]||'').toLowerCase();return rolePatch(c,(c.parsed.args[0]||'').toLowerCase(),v.startsWith('#')?{glow:true,glow_color:color(v)}:{glow:bool(v)})}})
registerCommand({name:'reset',description:'Reset appearance',source:'core',permissions:B,cooldown:{globalSeconds:5,userSeconds:5},handler:c=>overlay(c,{theme:'custom',font_family:'Inter',username_font_family:'Inter',font_size:24,username_font_size:20,font_weight:600,message_spacing:10,username_color:'#A970FF',message_color:'#F4F4F5',background_color:'#0B0B10',background_opacity:.72,bubble_color:'#18181B',bubble_opacity:.78,border_radius:16,animation:'slide',max_messages:12,fade_seconds:35,density:'normal',rainbow_mode:'off',glow_enabled:false,role_styles:{}})})
registerCommand({name:'help',description:'List commands',source:'core',permissions:ALL,cooldown:{globalSeconds:2,userSeconds:10},handler:async c=>{const q=c.parsed.args[0]?.toLowerCase(),all=listCommands(),f=q?all.find(x=>x.name===q||x.aliases?.includes(q)):null;return{message:f?`${c.parsed.prefix}${f.name} — ${f.description}`:`Commands: ${all.map(x=>c.parsed.prefix+x.name).join(', ')}`}}})
registerCommand({name:'plugins',description:'List enabled plugins',source:'core',permissions:ALL,handler:async c=>{const{data}=await c.admin.from('plugin_installations').select('plugin_id').eq('owner_id',c.ownerId).eq('enabled',true);return{message:data?.length?`Enabled plugins: ${data.map(x=>x.plugin_id).join(', ')}`:'No plugins enabled.'}}})
