import { FEATURE_KEYS } from '@/lib/features'

export async function getFeatureConfig(admin:any,ownerId:string,key:string){
  const row=await admin.from('streamer_feature_configs').select('config,updated_at').eq('owner_id',ownerId).eq('feature_key',key).maybeSingle()
  if(row.error)throw row.error
  return row.data||{config:{},updated_at:null}
}

export async function saveFeatureConfig(admin:any,ownerId:string,key:string,config:Record<string,unknown>){
  if(!FEATURE_KEYS.has(key))throw new Error('unknown_feature')
  const clean=JSON.parse(JSON.stringify(config||{}))
  const row=await admin.from('streamer_feature_configs').upsert({owner_id:ownerId,feature_key:key,config:clean,updated_at:new Date().toISOString()},{onConflict:'owner_id,feature_key'})
  if(row.error)throw row.error
  await audit(admin,ownerId,'feature.config.update','feature',key,{keys:Object.keys(clean)})
  return clean
}

export async function getFeatureSnapshot(admin:any,ownerId:string,key:string){
  const config=await getFeatureConfig(admin,ownerId,key)
  switch(key){
    case'unified_moderation':return{config:config.config,rules:(await rows(admin,'moderation_rules',ownerId,100)).data,actions:(await rows(admin,'moderation_actions',ownerId,100)).data}
    case'paid_events':{const o=await overlayId(admin,ownerId);const r=await admin.from('chat_events').select('id,source,event_type,chatter_name,message_text,event_data,created_at').eq('overlay_id',o).neq('event_type','message').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;return{config:config.config,events:r.data||[]}}
    case'featured_messages':{const o=await overlayId(admin,ownerId);const[f,m]=await Promise.all([admin.from('featured_messages').select('*').eq('owner_id',ownerId).order('featured_at',{ascending:false}).limit(20),admin.from('chat_events').select('id,source,chatter_name,message_text,created_at').eq('overlay_id',o).order('created_at',{ascending:false}).limit(80)]);if(f.error)throw f.error;if(m.error)throw m.error;return{config:config.config,featured:f.data||[],messages:m.data||[]}}
    case'qna':return{config:config.config,items:(await rows(admin,'qna_items',ownerId,100)).data}
    case'streamer_inbox':return inbox(admin,ownerId,config.config)
    case'custom_commands':{const r=await admin.from('command_configurations').select('*').eq('owner_id',ownerId).eq('source','custom').order('created_at',{ascending:false});if(r.error)throw r.error;return{config:config.config,commands:r.data||[]}}
    case'command_variables':return{config:config.config,variables:['user','display_name','platform','uptime','viewer_count','points','level','random_1_100']}
    case'chat_games':return{config:config.config,sessions:(await rows(admin,'chat_game_sessions',ownerId,50)).data}
    case'loyalty':case'currency':{const r=await admin.from('loyalty_accounts').select('viewer_id,xp,level,balance,updated_at').eq('owner_id',ownerId).order(key==='loyalty'?'xp':'balance',{ascending:false}).limit(100);if(r.error)throw r.error;return{config:config.config,leaderboard:r.data||[]}}
    case'viewer_cosmetics':{const r=await admin.from('viewer_cosmetics').select('viewer_id,cosmetics,updated_at').eq('owner_id',ownerId).limit(100);if(r.error)throw r.error;return{config:config.config,items:r.data||[]}}
    case'reward_store':return{config:config.config,items:(await rows(admin,'reward_store_items',ownerId,100)).data,redemptions:(await rows(admin,'reward_redemptions',ownerId,100)).data}
    case'cross_platform_polls':{const p=await rows(admin,'chat_polls',ownerId,30);const ids=(p.data||[]).map((x:any)=>x.id);let votes:any[]=[];if(ids.length){const v=await admin.from('chat_poll_votes').select('*').in('poll_id',ids);if(v.error)throw v.error;votes=v.data||[]}return{config:config.config,polls:p.data,votes}}
    case'predictions':{const p=await rows(admin,'predictions',ownerId,30);const ids=(p.data||[]).map((x:any)=>x.id);let entries:any[]=[];if(ids.length){const e=await admin.from('prediction_entries').select('*').in('prediction_id',ids);if(e.error)throw e.error;entries=e.data||[]}return{config:config.config,predictions:p.data,entries}}
    case'giveaways':{const g=await rows(admin,'giveaways',ownerId,30);const ids=(g.data||[]).map((x:any)=>x.id);let entries:any[]=[];if(ids.length){const e=await admin.from('giveaway_entries').select('*').in('giveaway_id',ids);if(e.error)throw e.error;entries=e.data||[]}return{config:config.config,giveaways:g.data,entries}}
    case'automation_builder':return{config:config.config,rules:(await rows(admin,'automation_rules',ownerId,100)).data}
    case'multi_overlays':return{config:config.config,overlays:(await rows(admin,'overlay_instances',ownerId,100)).data}
    case'template_marketplace':{const mine=await rows(admin,'overlay_templates',ownerId,100);const pub=await admin.from('overlay_templates').select('id,name,description,settings,owner_id,updated_at').eq('published',true).order('updated_at',{ascending:false}).limit(100);if(pub.error)throw pub.error;return{config:config.config,mine:mine.data,marketplace:pub.data||[]}}
    case'viewer_identity':{const ids=await admin.from('viewer_identities').select('id,viewer_id,platform,platform_user_id,platform_login,verified_at').order('verified_at',{ascending:false}).limit(200);if(ids.error)throw ids.error;return{config:config.config,identities:ids.data||[]}}
    case'moderator_accounts':return{config:config.config,members:(await rows(admin,'team_members',ownerId,100)).data}
    case'audit_log':return{config:config.config,events:(await rows(admin,'audit_events',ownerId,200)).data}
    case'stream_sessions':return{config:config.config,sessions:(await rows(admin,'stream_sessions',ownerId,100)).data}
    case'chat_analytics':return{config:config.config,...await analytics(admin,ownerId)}
    case'chat_heatmap':return{config:config.config,...await heatmap(admin,ownerId)}
    case'clip_suggestions':return{config:config.config,...await clipSuggestions(admin,ownerId)}
    case'plugin_dependencies':case'plugin_updates':case'plugin_health':case'plugin_logs':return pluginSnapshot(admin,ownerId,key,config.config)
    case'public_streamer_page':{const r=await admin.from('public_streamer_pages').select('*').eq('owner_id',ownerId).maybeSingle();if(r.error)throw r.error;return{config:config.config,page:r.data||null}}
    case'backup_snapshots':return{config:config.config,snapshots:(await rows(admin,'config_snapshots',ownerId,50)).data}
    case'health_page':case'reconnect_warnings':return{config:config.config,...await health(admin,ownerId)}
    case'status_notifications':return{config:config.config,notifications:(await rows(admin,'status_notifications',ownerId,50)).data}
    default:return{config:config.config,enabled:true,feature:key}
  }
}

export async function featureAction(admin:any,ownerId:string,key:string,body:any){
  const action=String(body?.action||'')
  if(action==='save_config')return{config:await saveFeatureConfig(admin,ownerId,key,body.config||{})}
  if(key==='unified_moderation')return moderationAction(admin,ownerId,action,body)
  if(key==='featured_messages')return featuredAction(admin,ownerId,action,body)
  if(key==='qna')return qnaAction(admin,ownerId,action,body)
  if(key==='custom_commands')return commandAction(admin,ownerId,action,body)
  if(key==='reward_store')return rewardAction(admin,ownerId,action,body)
  if(key==='cross_platform_polls')return pollAction(admin,ownerId,action,body)
  if(key==='predictions')return predictionAction(admin,ownerId,action,body)
  if(key==='giveaways')return giveawayAction(admin,ownerId,action,body)
  if(key==='automation_builder')return automationAction(admin,ownerId,action,body)
  if(key==='multi_overlays')return overlayAction(admin,ownerId,action,body)
  if(key==='template_marketplace')return templateAction(admin,ownerId,action,body)
  if(key==='moderator_accounts')return teamAction(admin,ownerId,action,body)
  if(key==='backup_snapshots'||key==='setup_export')return snapshotAction(admin,ownerId,action,body)
  if(key==='public_streamer_page')return publicPageAction(admin,ownerId,action,body)
  throw new Error('unsupported_action')
}

async function moderationAction(admin:any,ownerId:string,action:string,b:any){if(action==='create_rule'){const type=String(b.rule_type||'blocked_words'),allowed=['blocked_words','links','caps','length','repeated_text','rate'];if(!allowed.includes(type))throw new Error('invalid_rule_type');const r=await admin.from('moderation_rules').insert({owner_id:ownerId,name:String(b.name||type).slice(0,80),enabled:b.enabled!==false,rule_type:type,config:b.config||{},action:b.rule_action||{type:'hide'}}).select('*').single();if(r.error)throw r.error;await audit(admin,ownerId,'moderation.rule.create','moderation_rule',r.data.id,{});return r.data}if(action==='delete_rule'){const r=await admin.from('moderation_rules').delete().eq('owner_id',ownerId).eq('id',String(b.id||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function featuredAction(admin:any,ownerId:string,action:string,b:any){if(action==='feature'){const id=String(b.chat_event_id||'');const o=await overlayId(admin,ownerId);const check=await admin.from('chat_events').select('id').eq('id',id).eq('overlay_id',o).maybeSingle();if(check.error)throw check.error;if(!check.data)throw new Error('message_not_found');const seconds=Math.max(5,Math.min(3600,Number(b.seconds||60)));const r=await admin.from('featured_messages').upsert({owner_id:ownerId,chat_event_id:id,featured_at:new Date().toISOString(),expires_at:new Date(Date.now()+seconds*1000).toISOString()},{onConflict:'owner_id,chat_event_id'});if(r.error)throw r.error;return{ok:true}}if(action==='remove'){const r=await admin.from('featured_messages').delete().eq('owner_id',ownerId).eq('chat_event_id',String(b.chat_event_id||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function qnaAction(admin:any,ownerId:string,action:string,b:any){if(action==='set_status'){const status=String(b.status||'pending');if(!['pending','approved','featured','answered','rejected'].includes(status))throw new Error('invalid_status');const patch:any={status};if(status==='answered')patch.answered_at=new Date().toISOString();const r=await admin.from('qna_items').update(patch).eq('owner_id',ownerId).eq('id',String(b.id||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function commandAction(admin:any,ownerId:string,action:string,b:any){if(action==='save'){const name=String(b.name||'').toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,32);if(!name)throw new Error('invalid_command');const template=String(b.response_template||'').slice(0,500);if(!template)throw new Error('response_required');const payload={owner_id:ownerId,command_name:name,enabled:b.enabled!==false,aliases:Array.isArray(b.aliases)?b.aliases.slice(0,10):[],permissions:Array.isArray(b.permissions)&&b.permissions.length?b.permissions:['viewer'],global_cooldown_seconds:Math.max(0,Math.min(3600,Number(b.global_cooldown_seconds||1))),user_cooldown_seconds:Math.max(0,Math.min(3600,Number(b.user_cooldown_seconds||5))),source:'custom',plugin_id:null,response_template:template,variable_config:b.variable_config||{}};const r=await admin.from('command_configurations').upsert(payload,{onConflict:'owner_id,command_name'}).select('*').single();if(r.error)throw r.error;return r.data}if(action==='delete'){const r=await admin.from('command_configurations').delete().eq('owner_id',ownerId).eq('source','custom').eq('command_name',String(b.name||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function rewardAction(admin:any,ownerId:string,action:string,b:any){if(action==='save'){const name=String(b.name||'').trim().slice(0,80);if(!name)throw new Error('name_required');const payload={owner_id:ownerId,name,description:String(b.description||'').slice(0,300),cost:Math.max(0,Math.min(1_000_000_000,Number(b.cost||0))),enabled:b.enabled!==false,action:b.reward_action||{type:'none'},updated_at:new Date().toISOString()};let r;if(b.id)r=await admin.from('reward_store_items').update(payload).eq('owner_id',ownerId).eq('id',String(b.id)).select('*').single();else r=await admin.from('reward_store_items').insert(payload).select('*').single();if(r.error)throw r.error;return r.data}if(action==='delete'){const r=await admin.from('reward_store_items').delete().eq('owner_id',ownerId).eq('id',String(b.id||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function pollAction(admin:any,ownerId:string,action:string,b:any){if(action==='create'){const options=(Array.isArray(b.options)?b.options:[]).map((x:any)=>String(x).trim().slice(0,80)).filter(Boolean).slice(0,8),question=String(b.question||'').trim().slice(0,180);if(!question||options.length<2)throw new Error('invalid_poll');await admin.from('chat_polls').update({status:'closed',closed_at:new Date().toISOString()}).eq('owner_id',ownerId).eq('status','open');const r=await admin.from('chat_polls').insert({owner_id:ownerId,question,options,status:'open'}).select('*').single();if(r.error)throw r.error;return r.data}if(action==='close'){const r=await admin.from('chat_polls').update({status:'closed',closed_at:new Date().toISOString()}).eq('owner_id',ownerId).eq('id',String(b.id||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function predictionAction(admin:any,ownerId:string,action:string,b:any){if(action==='create'){const options=(Array.isArray(b.options)?b.options:[]).map((x:any)=>String(x).trim().slice(0,80)).filter(Boolean).slice(0,8),question=String(b.question||'').trim().slice(0,180);if(!question||options.length<2)throw new Error('invalid_prediction');await admin.from('predictions').update({status:'closed',closed_at:new Date().toISOString()}).eq('owner_id',ownerId).eq('status','open');const r=await admin.from('predictions').insert({owner_id:ownerId,question,options,status:'open'}).select('*').single();if(r.error)throw r.error;return r.data}if(action==='resolve'){const winning=Math.max(0,Number(b.winning_option||0));const r=await admin.from('predictions').update({status:'resolved',winning_option:winning,closed_at:new Date().toISOString()}).eq('owner_id',ownerId).eq('id',String(b.id||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function giveawayAction(admin:any,ownerId:string,action:string,b:any){if(action==='create'){const title=String(b.title||'').trim().slice(0,120);if(!title)throw new Error('title_required');await admin.from('giveaways').update({status:'closed',closed_at:new Date().toISOString()}).eq('owner_id',ownerId).eq('status','open');const r=await admin.from('giveaways').insert({owner_id:ownerId,title,status:'open'}).select('*').single();if(r.error)throw r.error;return r.data}if(action==='draw'){const id=String(b.id||'');const g=await admin.from('giveaways').select('id').eq('owner_id',ownerId).eq('id',id).single();if(g.error)throw g.error;const e=await admin.from('giveaway_entries').select('source,user_id,display_name').eq('giveaway_id',id);if(e.error)throw e.error;if(!e.data?.length)throw new Error('no_entries');const winner=e.data[Math.floor(Math.random()*e.data.length)];const r=await admin.from('giveaways').update({status:'closed',winner_source:winner.source,winner_user_id:winner.user_id,winner_name:winner.display_name,closed_at:new Date().toISOString()}).eq('owner_id',ownerId).eq('id',id);if(r.error)throw r.error;return{winner}}throw new Error('unsupported_action')}
async function automationAction(admin:any,ownerId:string,action:string,b:any){if(action==='save'){const payload={owner_id:ownerId,name:String(b.name||'Automation').slice(0,80),enabled:b.enabled!==false,trigger:b.trigger||{type:'chat_message'},conditions:Array.isArray(b.conditions)?b.conditions:[],actions:Array.isArray(b.actions)?b.actions.slice(0,12):[],updated_at:new Date().toISOString()};let r;if(b.id)r=await admin.from('automation_rules').update(payload).eq('owner_id',ownerId).eq('id',String(b.id)).select('*').single();else r=await admin.from('automation_rules').insert(payload).select('*').single();if(r.error)throw r.error;return r.data}if(action==='delete'){const r=await admin.from('automation_rules').delete().eq('owner_id',ownerId).eq('id',String(b.id||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function overlayAction(admin:any,ownerId:string,action:string,b:any){if(action==='create'){const name=String(b.name||'Overlay').trim().slice(0,60),slug=slugify(String(b.slug||name));if(!slug)throw new Error('invalid_slug');const base=await admin.from('overlays').select('*').eq('user_id',ownerId).single();if(base.error)throw base.error;const settings=b.settings&&typeof b.settings==='object'?b.settings:{};const r=await admin.from('overlay_instances').insert({owner_id:ownerId,name,slug,enabled:true,settings}).select('*').single();if(r.error)throw r.error;return r.data}if(action==='save'){const r=await admin.from('overlay_instances').update({name:String(b.name||'Overlay').slice(0,60),enabled:b.enabled!==false,settings:b.settings||{},updated_at:new Date().toISOString()}).eq('owner_id',ownerId).eq('id',String(b.id||'')).select('*').single();if(r.error)throw r.error;return r.data}if(action==='delete'){const r=await admin.from('overlay_instances').delete().eq('owner_id',ownerId).eq('id',String(b.id||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function templateAction(admin:any,ownerId:string,action:string,b:any){if(action==='publish'){const o=await admin.from('overlays').select('*').eq('user_id',ownerId).single();if(o.error)throw o.error;const{id,user_id,slug,created_at,updated_at,...settings}=o.data;const name=String(b.name||'Template').slice(0,80);const r=await admin.from('overlay_templates').upsert({owner_id:ownerId,name,description:String(b.description||'').slice(0,300),settings,published:true,updated_at:new Date().toISOString()},{onConflict:'owner_id,name'}).select('*').single();if(r.error)throw r.error;return r.data}if(action==='install'){const t=await admin.from('overlay_templates').select('settings').eq('id',String(b.id||'')).eq('published',true).single();if(t.error)throw t.error;const r=await admin.from('overlays').update(t.data.settings||{}).eq('user_id',ownerId);if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function teamAction(admin:any,ownerId:string,action:string,b:any){if(action==='add'){const member=String(b.member_user_id||'');const role=String(b.role||'moderator');if(!['admin','moderator','designer','developer','analyst','read_only'].includes(role))throw new Error('invalid_role');const r=await admin.from('team_members').upsert({owner_id:ownerId,member_user_id:member,role,enabled:true,permissions:b.permissions||[]},{onConflict:'owner_id,member_user_id'}).select('*').single();if(r.error)throw r.error;return r.data}if(action==='remove'){const r=await admin.from('team_members').delete().eq('owner_id',ownerId).eq('member_user_id',String(b.member_user_id||''));if(r.error)throw r.error;return{ok:true}}throw new Error('unsupported_action')}
async function snapshotAction(admin:any,ownerId:string,action:string,b:any){if(action==='create'||action==='export'){const snapshot=await buildSnapshot(admin,ownerId),label=String(b.label||new Date().toISOString()).slice(0,100);if(action==='create'){const r=await admin.from('config_snapshots').insert({owner_id:ownerId,label,snapshot}).select('id,label,created_at').single();if(r.error)throw r.error;return{snapshot:r.data}}return{snapshot}}if(action==='restore'){const r=await admin.from('config_snapshots').select('snapshot').eq('owner_id',ownerId).eq('id',String(b.id||'')).single();if(r.error)throw r.error;await restoreSnapshot(admin,ownerId,r.data.snapshot||{});return{ok:true}}throw new Error('unsupported_action')}
async function publicPageAction(admin:any,ownerId:string,action:string,b:any){if(action==='save'){const slug=slugify(String(b.slug||''));if(!slug)throw new Error('invalid_slug');const r=await admin.from('public_streamer_pages').upsert({owner_id:ownerId,slug,enabled:b.enabled===true,config:b.config||{},updated_at:new Date().toISOString()},{onConflict:'owner_id'}).select('*').single();if(r.error)throw r.error;return r.data}throw new Error('unsupported_action')}

async function rows(admin:any,table:string,ownerId:string,limit=100){const r=await admin.from(table).select('*').eq('owner_id',ownerId).order('created_at',{ascending:false}).limit(limit);if(r.error)throw r.error;return r}
async function overlayId(admin:any,ownerId:string){const r=await admin.from('overlays').select('id').eq('user_id',ownerId).single();if(r.error)throw r.error;return r.data.id}
async function inbox(admin:any,ownerId:string,config:any){const o=await overlayId(admin,ownerId),since=new Date(Date.now()-7*86400000).toISOString();const[p,q,m]=await Promise.all([admin.from('chat_events').select('id,source,event_type,chatter_name,message_text,event_data,created_at').eq('overlay_id',o).neq('event_type','message').gte('created_at',since).order('created_at',{ascending:false}).limit(100),admin.from('qna_items').select('*').eq('owner_id',ownerId).eq('status','pending').order('created_at',{ascending:false}).limit(100),admin.from('moderation_actions').select('*').eq('owner_id',ownerId).gte('created_at',since).order('created_at',{ascending:false}).limit(100)]);if(p.error)throw p.error;if(q.error)throw q.error;if(m.error)throw m.error;return{config,paid:p.data||[],questions:q.data||[],moderation:m.data||[]}}
async function analytics(admin:any,ownerId:string){const o=await overlayId(admin,ownerId),since=new Date(Date.now()-24*3600000).toISOString(),r=await admin.from('chat_events').select('source,chatter_user_id,chatter_name,created_at,event_type').eq('overlay_id',o).gte('created_at',since).order('created_at',{ascending:true});if(r.error)throw r.error;const messages=r.data||[],unique=new Set(messages.map((x:any)=>`${x.source}:${x.chatter_user_id}`)),bySource:Record<string,number>={},byHour:Record<string,number>={};for(const x of messages){bySource[x.source]=(bySource[x.source]||0)+1;const h=new Date(x.created_at).toISOString().slice(0,13)+':00';byHour[h]=(byHour[h]||0)+1}return{windowHours:24,messages:messages.length,uniqueChatters:unique.size,bySource,byHour}}
async function heatmap(admin:any,ownerId:string){const a=await analytics(admin,ownerId);return{bins:Object.entries(a.byHour).map(([time,count])=>({time,count})),messages:a.messages}}
async function clipSuggestions(admin:any,ownerId:string){const h=await heatmap(admin,ownerId),counts=h.bins.map((x:any)=>Number(x.count)),avg=counts.length?counts.reduce((a,b)=>a+b,0)/counts.length:0,threshold=Math.max(5,avg*2);return{threshold,suggestions:h.bins.filter((x:any)=>Number(x.count)>=threshold)}}
async function pluginSnapshot(admin:any,ownerId:string,key:string,config:any){const installs=await admin.from('plugin_installations').select('*').eq('owner_id',ownerId).order('updated_at',{ascending:false});if(installs.error)throw installs.error;const ids=(installs.data||[]).map((x:any)=>x.plugin_id);let versions:any[]=[],events:any[]=[];if(ids.length){const v=await admin.from('plugin_versions').select('plugin_id,version,manifest,checksum_sha256,created_at,marketplace_published').in('plugin_id',ids).order('created_at',{ascending:false});if(v.error)throw v.error;versions=v.data||[];const e=await admin.from('plugin_runtime_events').select('*').eq('owner_id',ownerId).in('plugin_id',ids).order('created_at',{ascending:false}).limit(200);if(e.error)throw e.error;events=e.data||[]}return{config,installs:installs.data||[],versions,events,mode:key}}
async function health(admin:any,ownerId:string){const[t,y,d,o]=await Promise.all([admin.from('twitch_credentials').select('expires_at,scopes').eq('user_id',ownerId).maybeSingle(),admin.from('youtube_credentials').select('expires_at,scopes').eq('user_id',ownerId).maybeSingle(),admin.from('discord_guild_connections').select('guild_id,guild_name,updated_at').eq('owner_id',ownerId).maybeSingle(),admin.from('overlays').select('slug,enabled,youtube_last_sync_at').eq('user_id',ownerId).single()]);return{integrations:{twitch:{connected:!!t.data,expires_at:t.data?.expires_at||null},youtube:{connected:!!y.data,expires_at:y.data?.expires_at||null},discord:{connected:!!d.data,guild:d.data?.guild_name||null},overlay:{connected:!!o.data?.enabled,slug:o.data?.slug||null,lastYoutubeSync:o.data?.youtube_last_sync_at||null}}}}
async function buildSnapshot(admin:any,ownerId:string){const[overlay,presets,commands,flags,configs,plugins,badges]=await Promise.all([admin.from('overlays').select('*').eq('user_id',ownerId).single(),admin.from('overlay_presets').select('*').eq('owner_id',ownerId),admin.from('command_configurations').select('*').eq('owner_id',ownerId),admin.from('streamer_feature_flags').select('flags').eq('owner_id',ownerId).maybeSingle(),admin.from('streamer_feature_configs').select('feature_key,config').eq('owner_id',ownerId),admin.from('plugin_installations').select('*').eq('owner_id',ownerId),admin.from('badge_assignments').select('*').eq('owner_id',ownerId)]);for(const r of[overlay,presets,commands,flags,configs,plugins,badges])if(r.error)throw r.error;return{version:1,created_at:new Date().toISOString(),overlay:overlay.data,presets:presets.data||[],commands:commands.data||[],feature_flags:flags.data?.flags||{},feature_configs:configs.data||[],plugins:plugins.data||[],badges:badges.data||[]}}
async function restoreSnapshot(admin:any,ownerId:string,s:any){if(s.overlay){const{id,user_id,slug,created_at,updated_at,...patch}=s.overlay;const r=await admin.from('overlays').update(patch).eq('user_id',ownerId);if(r.error)throw r.error}if(s.feature_flags){const r=await admin.from('streamer_feature_flags').upsert({owner_id:ownerId,flags:s.feature_flags,updated_at:new Date().toISOString()},{onConflict:'owner_id'});if(r.error)throw r.error}}
async function audit(admin:any,ownerId:string,action:string,targetType:string,targetId:string|null,metadata:any){const r=await admin.from('audit_events').insert({owner_id:ownerId,actor_user_id:ownerId,action,target_type:targetType,target_id:targetId,metadata});if(r.error)throw r.error}
function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)}
