'use client'

import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import DashboardNav from '@/components/DashboardNav'
import { PluginDashboardSurface } from '@/components/PluginSurface'
import { createClient } from '@/lib/supabase/client'

type Manifest={id:string;name:string;version:string;author:string;description?:string;apiVersion:string;permissions:string[]}
type Installation={id:string;plugin_id:string;version:string;enabled:boolean;source:string;plugins?:{name:string;author:string;description:string}|null}
type MarketPlugin={id:string;name:string;author:string;description:string;api_version:string;latest_version:string|null;category:string;tags:string[];featured:boolean;verified:boolean;install_count:number;published_at:string|null}

export default function PluginsPage(){
 const supabase=useMemo(()=>createClient(),[]),router=useRouter()
 const[items,setItems]=useState<Installation[]>([]),[market,setMarket]=useState<MarketPlugin[]>([]),[admin,setAdmin]=useState(false),[status,setStatus]=useState('Loading plugins…'),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Manifest|null>(null),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[category,setCategory]=useState('all')
 const[publishFile,setPublishFile]=useState<File|null>(null),[publishMeta,setPublishMeta]=useState({category:'other',tags:'',featured:false})
 async function load(){
  const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth');return}
  const[i,m,a]=await Promise.all([
   supabase.from('plugin_installations').select('id,plugin_id,version,enabled,source,plugins(name,author,description)').eq('owner_id',user.id).order('installed_at',{ascending:false}),
   supabase.from('plugins').select('id,name,author,description,api_version,latest_version,category,tags,featured,verified,install_count,published_at').eq('marketplace_status','published').order('featured',{ascending:false}).order('published_at',{ascending:false}),
   supabase.from('platform_admins').select('user_id').eq('user_id',user.id).maybeSingle(),
  ])
  setItems((i.data||[]) as any);setMarket((m.data||[]) as MarketPlugin[]);setAdmin(!!a.data);setStatus(i.error?.message||m.error?.message||'Plugin studio ready')
 }
 useEffect(()=>{load()},[])
 async function choose(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]||null;setFile(f);setPreview(null);if(!f)return;setBusy(true);setStatus('Inspecting plugin package…');const form=new FormData();form.set('file',f);const res=await fetch('/api/plugins/inspect',{method:'POST',body:form}),body=await res.json();setBusy(false);if(!res.ok){setStatus(body.error||'Plugin rejected');return}setPreview(body.manifest);setStatus('Review permissions before install')}
 async function installUpload(){if(!file||!preview)return;setBusy(true);const form=new FormData();form.set('file',file);const res=await fetch('/api/plugins/install',{method:'POST',body:form}),body=await res.json();setBusy(false);if(!res.ok){setStatus(body.error||'Install failed');return}setFile(null);setPreview(null);setStatus(`${body.manifest.name} installed disabled`);await load()}
 async function installMarket(p:MarketPlugin){setBusy(true);setStatus(`Installing ${p.name}…`);const res=await fetch('/api/plugins/marketplace/install',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pluginId:p.id,version:p.latest_version})}),body=await res.json();setBusy(false);setStatus(res.ok?`${p.name} installed disabled`:body.error||'Marketplace install failed');if(res.ok)await load()}
 async function publish(){if(!publishFile)return;setBusy(true);setStatus('Validating and publishing tested plugin…');const form=new FormData();form.set('file',publishFile);form.set('category',publishMeta.category);form.set('tags',publishMeta.tags);form.set('featured',String(publishMeta.featured));const res=await fetch('/api/plugins/marketplace/publish',{method:'POST',body:form}),body=await res.json();setBusy(false);setStatus(res.ok?`${body.plugin.name} published to Marketplace`:body.error||'Publish failed');if(res.ok){setPublishFile(null);await load()}}
 async function toggle(i:Installation){const r=await supabase.from('plugin_installations').update({enabled:!i.enabled,updated_at:new Date().toISOString()}).eq('id',i.id);setStatus(r.error?r.error.message:`${i.plugin_id} ${i.enabled?'disabled':'enabled'}`);if(!r.error){await load();window.location.reload()}}
 async function uninstall(i:Installation){if(!confirm(`Uninstall ${i.plugin_id}?`))return;await supabase.from('plugin_storage').delete().eq('plugin_id',i.plugin_id);const r=await supabase.from('plugin_installations').delete().eq('id',i.id);setStatus(r.error?r.error.message:'Plugin uninstalled');if(!r.error)await load()}
 async function signOut(){await supabase.auth.signOut();router.replace('/')}
 const categories=['all',...Array.from(new Set(market.map(p=>p.category)))],filtered=market.filter(p=>(category==='all'||p.category===category)&&(`${p.name} ${p.author} ${p.description} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())))
 return <><DashboardNav onSignOut={signOut}/><main className="app-main">
  <section className="dashboard-hero"><div><span className="eyebrow">PLUGIN MARKETPLACE</span><h1>Install tested features in one click.</h1><p>Browse CTCI-approved plugins, install them disabled by default, or upload your own ZIP for private testing. Developers and coding AIs get a documented API contract.</p></div><div className="actions"><Link className="btn primary" href="/docs/plugins">Plugin docs</Link><a className="btn" href="/api/plugins/spec">AI spec</a></div></section>
  <section className="panel"><div className="section-head"><div><span className="section-kicker">MARKETPLACE</span><h2>Approved plugins</h2><p className="muted">Only versions published by the CTCI owner appear here.</p></div><span className="status success">{market.length} published</span></div><div className="row"><div className="field"><label>Search</label><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search plugins, authors, tags…"/></div><div className="field"><label>Category</label><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></div></div><div className="plugin-list">{filtered.length===0?<div className="plugin-card"><strong>No marketplace plugins yet</strong><p className="small muted">Publish your first tested plugin below.</p></div>:filtered.map(p=><article className="plugin-card" key={p.id}><div className="plugin-title"><div><strong>{p.name}</strong><div className="small muted">v{p.latest_version||'?'} · {p.author} · {p.category}</div></div><div className="actions">{p.verified?<span className="status success">Verified</span>:null}{p.featured?<span className="status">Featured</span>:null}</div></div><p className="muted">{p.description||'No description.'}</p><div className="role-grid">{(p.tags||[]).map(t=><span className="chip" key={t}>{t}</span>)}</div><div className="actions"><button className="btn primary" disabled={busy||!p.latest_version} onClick={()=>installMarket(p)}>Install</button><span className="small muted">{p.install_count||0} installs</span></div></article>)}</div></section>
  <PluginDashboardSurface placement="plugins"/>
  <div className="studio-layout" style={{marginTop:20}}><section className="studio-content">
   <section className="panel"><div className="section-head"><div><span className="section-kicker">INSTALLED</span><h2>Your plugins</h2><p className="muted">Marketplace and private plugins stay disabled until you enable them. Enabled plugins may add safe UI cards and OBS widgets.</p></div><span className="status success">{items.filter(i=>i.enabled).length} enabled</span></div><div className="plugin-list">{items.length===0?<div className="plugin-card"><strong>No plugins installed</strong></div>:items.map(i=><article className="plugin-card" key={i.id}><div className="plugin-title"><div><strong>{i.plugins?.name||i.plugin_id}</strong><div className="small muted">v{i.version} · {i.source}</div></div><span className={`status ${i.enabled?'success':''}`}>{i.enabled?'Enabled':'Disabled'}</span></div><p className="muted">{i.plugins?.description||'No description.'}</p><div className="actions"><button className={`btn ${i.enabled?'':'primary'}`} onClick={()=>toggle(i)}>{i.enabled?'Disable':'Enable'}</button><button className="btn ghost" onClick={()=>uninstall(i)}>Uninstall</button></div></article>)}</div></section>
   <section className="panel"><div className="section-head"><div><span className="section-kicker">PRIVATE TESTING</span><h2>Upload plugin ZIP</h2><p className="muted">Inspect and install a development package only for your account.</p></div></div><div className="field"><label>Plugin ZIP</label><input type="file" accept=".zip,application/zip" onChange={choose}/></div>{preview?<div className="plugin-card"><div className="plugin-title"><div><strong>{preview.name}</strong><div className="small muted">v{preview.version} · {preview.author}</div></div><span className="status">API v{preview.apiVersion}</span></div><p className="muted">{preview.description||'No description.'}</p><div className="role-grid">{preview.permissions.map(p=><span className="chip" key={p}>{p}</span>)}</div><div className="actions"><button className="btn primary" disabled={busy} onClick={installUpload}>Approve & install privately</button></div></div>:null}</section>
   {admin?<section className="panel"><div className="section-head"><div><span className="section-kicker">PLATFORM OWNER</span><h2>Publish tested plugin</h2><p className="muted">Only your owner account can publish. Published versions are immutable; changed bytes require a version bump.</p></div><span className="status success">Owner</span></div><div className="field"><label>Tested plugin ZIP</label><input type="file" accept=".zip,application/zip" onChange={e=>setPublishFile(e.target.files?.[0]||null)}/></div><div className="row"><div className="field"><label>Category</label><input value={publishMeta.category} onChange={e=>setPublishMeta(v=>({...v,category:e.target.value}))} placeholder="chat, moderation, visuals…"/></div><div className="field"><label>Tags</label><input value={publishMeta.tags} onChange={e=>setPublishMeta(v=>({...v,tags:e.target.value}))} placeholder="commands, fun, overlay"/></div></div><label className="check"><input type="checkbox" checked={publishMeta.featured} onChange={e=>setPublishMeta(v=>({...v,featured:e.target.checked}))}/>Feature this plugin</label><div className="actions"><button className="btn primary" disabled={!publishFile||busy} onClick={publish}>Validate & publish</button></div></section>:null}
  </section><aside className="studio-sidebar"><section className="panel"><span className="section-kicker">DEVELOPER PORTAL</span><h2>Build for CTCI</h2><p className="muted">The docs include commands, dashboard cards, settings fields, OBS widgets, capabilities, storage, config, package validation, and AI-ready examples.</p><div className="actions"><Link className="btn primary" href="/docs/plugins">Read docs</Link><a className="btn" href="/api/plugins/spec">JSON spec</a></div></section><section className="panel"><h3>Safety status</h3><p className="muted">Declarative plugin UI is rendered by CTCI. Plugin HTML and JavaScript are never injected into the dashboard or OBS DOM. Dynamic plugin JavaScript still requires an isolated runtime.</p><div className="divider"/><span className="status">{status}</span></section></aside></div>
 </main></>}
