'use client'

import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

type Manifest={id:string;name:string;version:string;author:string;description?:string;apiVersion:string;permissions:string[]}
type Installation={id:string;plugin_id:string;version:string;enabled:boolean;source:string;plugins?:{name:string;author:string;description:string}|null}

export default function PluginsPage(){
 const supabase=useMemo(()=>createClient(),[]),router=useRouter();const[items,setItems]=useState<Installation[]>([]),[status,setStatus]=useState('Loading…'),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Manifest|null>(null),[busy,setBusy]=useState(false)
 async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth');return}const r=await supabase.from('plugin_installations').select('id,plugin_id,version,enabled,source,plugins(name,author,description)').eq('owner_id',user.id).order('installed_at',{ascending:false});if(r.error)setStatus(r.error.message);else{setItems((r.data||[]) as any);setStatus('Ready')}}
 useEffect(()=>{load()},[])
 async function choose(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]||null;setFile(f);setPreview(null);if(!f)return;setBusy(true);setStatus('Inspecting plugin…');const form=new FormData();form.set('file',f);const res=await fetch('/api/plugins/inspect',{method:'POST',body:form}),body=await res.json();setBusy(false);if(!res.ok){setStatus(body.error||'Plugin rejected');return}setPreview(body.manifest);setStatus('Review permissions, then install')}
 async function install(){if(!file||!preview)return;setBusy(true);setStatus('Installing disabled-by-default…');const form=new FormData();form.set('file',file);const res=await fetch('/api/plugins/install',{method:'POST',body:form}),body=await res.json();setBusy(false);if(!res.ok){setStatus(body.error||'Install failed');return}setFile(null);setPreview(null);setStatus(`${body.manifest.name} installed disabled`);await load()}
 async function toggle(i:Installation){setStatus(`${i.enabled?'Disabling':'Enabling'} ${i.plugin_id}…`);const r=await supabase.from('plugin_installations').update({enabled:!i.enabled,updated_at:new Date().toISOString()}).eq('id',i.id);if(r.error)setStatus(r.error.message);else await load()}
 async function uninstall(i:Installation){if(!confirm(`Uninstall ${i.plugin_id}? Plugin-scoped storage will be removed.`))return;setStatus(`Uninstalling ${i.plugin_id}…`);await supabase.from('plugin_storage').delete().eq('plugin_id',i.plugin_id);const r=await supabase.from('plugin_installations').delete().eq('id',i.id);if(r.error)setStatus(r.error.message);else await load()}
 return <main className="shell"><nav className="nav"><div className="brand">CTCI <span>Plugins</span></div><div className="actions"><Link className="btn" href="/dashboard">Overlay</Link><Link className="btn" href="/dashboard/commands">Commands</Link></div></nav><section className="panel"><div className="section-head"><div><h2>Plugin manager</h2><p className="muted">Upload validated plugin packages. Uploaded JavaScript remains sandbox-pending and is never executed in the Vercel process.</p></div><span className="status">{status}</span></div><div className="field"><label>Upload plugin ZIP</label><input type="file" accept=".zip,application/zip" onChange={choose}/></div>{preview&&<div className="plugin-card"><div className="plugin-title"><strong>{preview.name} <span className="muted">v{preview.version}</span></strong><span className="status">API v{preview.apiVersion}</span></div><p>{preview.description||'No description.'}</p><p className="small muted">Author: {preview.author}</p><h3>Requested permissions</h3><div className="role-grid">{preview.permissions.map(p=><span className="chip" key={p}>{p}</span>)}</div><div className="actions"><button className="btn primary" disabled={busy} onClick={install}>Approve & install disabled</button><button className="btn" onClick={()=>{setFile(null);setPreview(null)}}>Cancel</button></div></div>}<hr className="divider"/><h2>Installed plugins</h2><div className="plugin-list">{items.length===0&&<p className="muted">No plugins installed yet.</p>}{items.map(i=><article className="plugin-card" key={i.id}><div className="plugin-title"><div><strong>{i.plugins?.name||i.plugin_id}</strong><div className="small muted">v{i.version} · {i.source} · {i.plugins?.author||'Unknown author'}</div></div><span className="status">{i.enabled?'Enabled':'Disabled'}</span></div><p className="muted">{i.plugins?.description||'No description.'}</p><div className="actions"><button className="btn" onClick={()=>toggle(i)}>{i.enabled?'Disable':'Enable'}</button><button className="btn danger" onClick={()=>uninstall(i)}>Uninstall</button></div><p className="small muted">Execution status: sandbox runtime pending. Enable state is stored now so the runtime can activate it safely later.</p></article>)}</div></section></main>
}
