services:
  ctci-discord-worker:
    build: .
    container_name: ctci-discord-worker
    restart: unless-stopped
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      SUPABASE_SECRET_KEY: ${SUPABASE_SECRET_KEY}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
