import Link from 'next/link'

const caps=['chat.read','commands.register','typography.write','theme.write','overlay.write','storage.read','storage.write','config.read','config.write','ui.render','events.subscribe','sounds.play']

export default function PluginDocs(){
  return <main className="app-main"><section className="dashboard-hero"><div><span className="eyebrow">CTCI PLUGIN SDK</span><h1>Build plugins for streamers and AI coding agents.</h1><p>CTCI plugins are ZIP packages with a strict manifest, explicit capabilities, and a bundled JavaScript entrypoint. This page is the human-readable contract; the machine-readable version lives at <code>/api/plugins/spec</code>.</p></div><div className="actions"><Link className="btn primary" href="/dashboard/plugins">Open marketplace</Link><a className="btn" href="/api/plugins/spec">Machine-readable spec</a></div></section>
  <div className="studio-layout"><section className="studio-content">
    <section className="panel"><span className="section-kicker">1 · PACKAGE</span><h2>Required ZIP layout</h2><pre><code>{`my-plugin.zip\n├── plugin.json\n└── dist/\n    └── index.js`}</code></pre><p className="muted">The archive may contain supporting assets, but the executable entry must be bundled JavaScript under <code>dist/</code>. Do not ship <code>node_modules</code>, secrets, private keys, or environment files.</p></section>
    <section className="panel"><span className="section-kicker">2 · MANIFEST</span><h2>plugin.json</h2><pre><code>{`{\n  "id": "hello-chat",\n  "name": "Hello Chat",\n  "version": "1.0.0",\n  "author": "Your Name",\n  "description": "Adds a hello command",\n  "apiVersion": "1",\n  "entry": "dist/index.js",\n  "permissions": ["commands.register"],\n  "commands": [\n    { "name": "hello", "description": "Say hello", "permissions": ["viewer"] }\n  ]\n}`}</code></pre><p className="muted">IDs are lowercase slugs, versions use SemVer, API version is currently <code>1</code>, and permissions must come from the official capability list.</p></section>
    <section className="panel"><span className="section-kicker">3 · CODE</span><h2>Minimal plugin</h2><pre><code>{`import { definePlugin } from '@ctci/plugin-sdk'\n\nexport default definePlugin({\n  id: 'hello-chat',\n  apiVersion: '1',\n  async onLoad(ctx) {\n    ctx.commands.register({\n      name: 'hello',\n      description: 'Say hello',\n      permissions: ['viewer'],\n      async handler() {\n        return { message: 'Hello from CTCI!' }\n      }\n    })\n  }\n})`}</code></pre></section>
    <section className="panel"><span className="section-kicker">4 · CAPABILITIES</span><h2>Permission model</h2><div className="role-grid">{caps.map(c=><span className="chip" key={c}>{c}</span>)}</div><p className="muted">Ask only for what your plugin needs. CTCI must never expose Supabase secret keys, Twitch/Discord OAuth tokens, another streamer's storage, the host filesystem, or arbitrary process/environment access to plugin code.</p></section>
    <section className="panel"><span className="section-kicker">5 · AI CODING CONTRACT</span><h2>Prompt an AI safely</h2><p>Give your coding AI the URL <code>/api/plugins/spec</code> and tell it to treat that JSON as authoritative. It should generate a ZIP-ready plugin that validates against API v1, uses only declared capabilities, contains no secrets, and bundles its entry to <code>dist/index.js</code>.</p><pre><code>{`Build a CTCI API v1 plugin.\nUse the authoritative specification from /api/plugins/spec.\nReturn plugin.json, source code, build instructions, and the final ZIP layout.\nDo not use undeclared capabilities, filesystem/process/env access, eval, direct Supabase access, or OAuth tokens.`}</code></pre></section>
    <section className="panel"><span className="section-kicker">6 · REVIEW & MARKETPLACE</span><h2>Publishing workflow</h2><p className="muted">Developers test locally/package the ZIP → upload it to CTCI for inspection → you review/test it → a platform admin publishes the tested version → streamers see it in Marketplace and can install it disabled by default.</p></section>
  </section><aside className="studio-sidebar"><section className="panel"><h3>Validation limits</h3><p className="muted">10 MB compressed, 500 archive entries, 256 KB manifest, no traversal paths, no secrets/private keys, SemVer required, exact API v1 compatibility.</p></section><section className="panel"><h3>Current execution status</h3><p className="muted">Marketplace installation and permission grants are supported. Arbitrary uploaded JavaScript is intentionally not executed inside the Vercel web process until CTCI has a safe isolated runtime.</p></section></aside></div></main>
}
