import Link from 'next/link'

const caps=['chat.read','commands.register','typography.write','theme.write','overlay.write','storage.read','storage.write','config.read','config.write','ui.render','events.subscribe','sounds.play']

export default function PluginDocs(){
  return <main className="app-main"><section className="dashboard-hero"><div><span className="eyebrow">CTCI PLUGIN SDK</span><h1>Build plugins for chat, dashboard UI, OBS, commands and more.</h1><p>CTCI plugins are ZIP packages with a strict manifest, explicit capabilities, per-streamer config/storage, declarative UI extensions, and a bundled JavaScript entrypoint for the future isolated runtime. This page is the human-readable contract; coding AIs should also read <code>/api/plugins/spec</code>.</p></div><div className="actions"><Link className="btn primary" href="/dashboard/plugins">Open marketplace</Link><a className="btn" href="/api/plugins/spec">Machine-readable spec</a></div></section>
  <div className="studio-layout"><section className="studio-content">
    <section className="panel"><span className="section-kicker">1 · PACKAGE</span><h2>Required ZIP layout</h2><pre><code>{`my-plugin.zip\n├── plugin.json\n└── dist/\n    └── index.js`}</code></pre><p className="muted">The archive may contain supporting assets, but the executable entry must be bundled JavaScript under <code>dist/</code>. Do not ship <code>node_modules</code>, secrets, private keys, or environment files. Current limits: 10 MB compressed, 50 MB total expanded, 16 MB per expanded file, 500 entries, ZIP64 rejected.</p></section>

    <section className="panel"><span className="section-kicker">2 · MANIFEST</span><h2>plugin.json</h2><pre><code>{`{\n  "id": "stream-panel",\n  "name": "Stream Panel",\n  "version": "1.0.0",\n  "author": "Your Name",\n  "description": "Adds dashboard controls and an OBS label",\n  "apiVersion": "1",\n  "entry": "dist/index.js",\n  "permissions": ["ui.render", "config.read", "config.write"],\n  "ui": {\n    "dashboard": [],\n    "overlay": []\n  }\n}`}</code></pre><p className="muted">IDs are lowercase slugs. Versions use SemVer. Once a Marketplace version is published, the same <code>id + version</code> can never be replaced with different bytes—bump the version.</p></section>

    <section className="panel"><span className="section-kicker">3 · DASHBOARD UI</span><h2>Add cards and controls to CTCI</h2><p className="muted">Plugins never inject raw HTML/React. They declare components in <code>plugin.json</code>, CTCI validates them, then CTCI renders the controls. This protects streamers from token theft, XSS and broken dashboards.</p><pre><code>{`{\n  "permissions": ["ui.render", "config.read", "config.write"],\n  "ui": {\n    "dashboard": [\n      {\n        "id": "stream-tools",\n        "title": "Stream Tools",\n        "description": "Settings from my plugin",\n        "placement": "plugins",\n        "blocks": [\n          { "type": "heading", "text": "Plugin status", "level": 3 },\n          { "type": "text", "text": "Everything is ready." },\n          { "type": "stat", "label": "Mode", "value": "LIVE" },\n          { "type": "badge", "text": "Connected" },\n          { "type": "progress", "label": "Goal", "value": 64, "max": 100 },\n          { "type": "link", "label": "Open docs", "href": "/docs/plugins", "variant": "primary" }\n        ],\n        "settings": [\n          { "key": "showLabel", "label": "Show OBS label", "type": "boolean", "default": true },\n          { "key": "accent", "label": "Accent", "type": "color", "default": "#9147ff" },\n          { "key": "title", "label": "Custom title", "type": "text", "default": "Hello chat" },\n          { "key": "size", "label": "Size", "type": "number", "default": 24, "min": 8, "max": 100 },\n          { "key": "style", "label": "Style", "type": "select", "default": "neon",\n            "options": [{"label":"Neon","value":"neon"},{"label":"Clean","value":"clean"}] }\n        ]\n      }\n    ]\n  }\n}`}</code></pre><p className="muted">Dashboard placements: <code>overview</code>, <code>plugins</code>, <code>commands</code>, <code>badges</code>. Block types: <code>heading</code>, <code>text</code>, <code>stat</code>, <code>badge</code>, <code>image</code>, <code>link</code>, <code>progress</code>, <code>divider</code>. Settings require <code>config.read</code> + <code>config.write</code> and are stored per streamer.</p></section>

    <section className="panel"><span className="section-kicker">4 · OBS UI</span><h2>Add safe overlay widgets</h2><p className="muted">Enabled plugins can layer widgets over the transparent OBS Browser Source. Positions and sizes are percentages so widgets scale with the browser source.</p><pre><code>{`{\n  "permissions": ["ui.render"],\n  "ui": {\n    "overlay": [\n      {\n        "id": "watermark",\n        "type": "text",\n        "text": "My Plugin",\n        "x": 2, "y": 2, "width": 25,\n        "color": "#ffffff",\n        "fontSize": 20,\n        "zIndex": 10\n      },\n      {\n        "id": "logo",\n        "type": "image",\n        "src": "https://example.com/logo.png",\n        "x": 80, "y": 2, "width": 16, "height": 16,\n        "opacity": 0.9\n      },\n      {\n        "id": "goal",\n        "type": "progress",\n        "x": 5, "y": 90, "width": 50, "height": 3,\n        "value": 75, "max": 100\n      }\n    ]\n  }\n}`}</code></pre><p className="muted">Widget types: <code>text</code>, <code>image</code>, <code>box</code>, <code>progress</code>. Remote images must use HTTPS. Raw HTML, raw CSS and JavaScript URLs are rejected. Enabled overlay contributions refresh automatically.</p></section>

    <section className="panel"><span className="section-kicker">5 · COMMANDS</span><h2>Add chat commands</h2><pre><code>{`{\n  "permissions": ["commands.register"],\n  "commands": [\n    { "name": "hello", "aliases": ["hi"], "description": "Say hello", "permissions": ["viewer"] }\n  ]\n}`}</code></pre><pre><code>{`import { definePlugin } from '@ctci/plugin-sdk'\n\nexport default definePlugin({\n  id: 'hello-chat',\n  apiVersion: '1',\n  async onLoad(ctx) {\n    ctx.commands.register({\n      name: 'hello',\n      aliases: ['hi'],\n      description: 'Say hello',\n      permissions: ['viewer'],\n      async handler() { return { message: 'Hello from CTCI!' } }\n    })\n  }\n})`}</code></pre><p className="muted">The command manifest is validated today. Dynamic uploaded JavaScript command handlers will run only when the isolated plugin runtime is enabled; arbitrary JS is never executed inside the main Vercel web process.</p></section>

    <section className="panel"><span className="section-kicker">6 · CAPABILITIES</span><h2>Permission model</h2><div className="role-grid">{caps.map(c=><span className="chip" key={c}>{c}</span>)}</div><p className="muted"><code>ui.render</code> is required for dashboard/OBS contributions. Settings additionally require <code>config.read</code> and <code>config.write</code>. Ask only for what your plugin needs. CTCI never exposes Supabase secret keys, Twitch/Discord OAuth tokens, another streamer's data, the host filesystem, or process/environment access.</p></section>

    <section className="panel"><span className="section-kicker">7 · CONFIG & STORAGE</span><h2>Per-streamer state</h2><p className="muted">Each installation gets isolated configuration and plugin storage. Dashboard settings are validated against the manifest before CTCI writes them. A plugin cannot write another plugin's configuration or another streamer's installation.</p><pre><code>{`// Future isolated runtime API\nconst enabled = await ctx.config.get('showLabel')\nawait ctx.storage.set('counter', 42)\nconst counter = await ctx.storage.get('counter')`}</code></pre></section>

    <section className="panel"><span className="section-kicker">8 · AI CODING CONTRACT</span><h2>Prompt Claude, Codex or another coding AI</h2><p>Give the AI the production <code>/api/plugins/spec</code> endpoint and tell it that JSON is authoritative.</p><pre><code>{`Build a complete CTCI API v1 plugin.\nRead https://chromachat.syntax-xxx.is-a.dev/api/plugins/spec and treat it as authoritative.\nUse declarative ui.dashboard/ui.overlay for visual features.\nReturn plugin.json, source code, build instructions and final ZIP layout.\nUse only declared capabilities.\nNever use eval, raw HTML injection, process/env, filesystem access, direct Supabase access or OAuth tokens.\nIf changing an already-published release, bump the SemVer version.`}</code></pre></section>

    <section className="panel"><span className="section-kicker">9 · REVIEW & MARKETPLACE</span><h2>Publishing workflow</h2><p className="muted">Developer builds ZIP → private upload/inspection → streamer tests it → CTCI owner reviews the exact package → owner publishes that exact version → Marketplace users install the approved immutable release disabled by default. Private plugin IDs are isolated by developer account and cannot overwrite Marketplace packages.</p></section>

    <section className="panel"><span className="section-kicker">10 · WHAT PLUGINS CAN EXTEND</span><h2>Extension map</h2><div className="role-grid"><span className="chip">Chat commands</span><span className="chip">Dashboard cards</span><span className="chip">Settings panels</span><span className="chip">OBS widgets</span><span className="chip">Themes</span><span className="chip">Typography</span><span className="chip">Overlay settings</span><span className="chip">Sounds</span><span className="chip">Events</span><span className="chip">Plugin storage</span><span className="chip">Per-streamer config</span></div><p className="muted">The long-term runtime is capability-based: dynamic logic will call CTCI APIs rather than receiving direct access to the app/database. Vercel Sandbox is the intended isolation option for truly untrusted execution while keeping the platform Vercel + Supabase only.</p></section>
  </section><aside className="studio-sidebar"><section className="panel"><h3>Validation limits</h3><p className="muted">10 MB compressed · 50 MB expanded · 16 MB/file · 500 archive entries · 256 KB manifest · no traversal · no secrets/private keys · SemVer · exact API v1.</p></section><section className="panel"><h3>UI execution status</h3><p className="muted">Declarative dashboard cards, settings fields, and OBS widgets are supported and rendered by CTCI. Plugin-provided HTML/React/JS is not injected into the UI.</p></section><section className="panel"><h3>Dynamic code status</h3><p className="muted">Arbitrary uploaded JavaScript remains disabled in the main Vercel process. Dynamic handlers will use an isolated capability runtime rather than <code>eval()</code>.</p></section></aside></div></main>
}
