'use client'

import Link from 'next/link'
import { useEffect,useMemo,useState } from 'react'
import { useRouter } from 'next/navigation'
import DashboardNav from '@/components/DashboardNav'
import { createClient } from '@/lib/supabase/client'

type Verification={status:string;testedAt:string|null;testKind:string|null;details:any}
type Feature={key:string;name:string;group:string;description:string;requirements:string[];maturity:'ready'|'foundation'|'integration';release:'stable'|'beta';verification:Verification|null}
type OpenAIStatus={configured:boolean;last4:string|null;validatedAt:string|null}

const requirementLabel:Record<string,string>={none:'No extra setup',twitch:'Twitch connection',youtube:'YouTube OAuth',discord:'Discord bot',obs:'Local OBS WebSocket bridge',spotify:'Spotify OAuth app',streamelements:'StreamElements credentials',streamlabs:'Streamlabs OAuth/API',ai:'Your OpenAI API key',email:'Email provider/API',translation:'Translation provider (optional)'}
const runtimeLabel:Record<string,string>={ready:'Runtime implemented',foundation:'Runtime/foundation implemented',integration:'External integration required'}

export default function FeaturesPage(){
  const router=useRouter(),[features,setFeatures]=useState<Feature[]>([]),[flags,setFlags]=useState<Record<string,boolean>>({}),[status,setStatus]=useState('Loading features…'),[busy,setBusy]=useState('')
  const[openAI,setOpenAI]=useState<OpenAIStatus>({configured:false,last4:null,validatedAt:null}),[apiKey,setApiKey]=useState(''),[keyBusy,setKeyBusy]=useState(false),[keyStatus,setKeyStatus]=useState('Loading OpenAI key status…')
  useEffect(()=>{void(async()=>{const sb=createClient(),{data:{user}}=await sb.auth.getUser();if(!user){router.replace('/auth');return}const[featureRes,keyRes]=await Promise.all([fetch('/api/features',{cache:'no-store'}),fetch('/api/settings/openai',{cache:'no-store'})]),b=await featureRes.json().catch(()=>({})),k=await keyRes.json().catch(()=>({}));if(!featureRes.ok){setStatus(b.error||'Could not load features');return}setFeatures(b.features||[]);setFlags(b.flags||{});setStatus('Optional features default to OFF. STABLE requires a recorded end-to-end or streamer test; everything else remains BETA.');if(keyRes.ok){setOpenAI({configured:k.configured===true,last4:k.last4||null,validatedAt:k.validatedAt||null});setKeyStatus(k.configured?`OpenAI key connected ••••${k.last4||''}`:'No OpenAI key saved.')}else setKeyStatus(k.error||'Could not load OpenAI key status')})()},[router])
  const groups=useMemo(()=>{const map=new Map<string,Feature[]>();for(const f of features){const list=map.get(f.group)||[];list.push(f);map.set(f.group,list)}return[...map.entries()]},[features])
  async function toggle(key:string,enabled:boolean){setBusy(key);setStatus(`${enabled?'Enabling':'Disabling'} feature…`);try{const r=await fetch('/api/features',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,enabled})}),b=await r.json().catch(()=>({}));if(!r.ok){setStatus(b.error||'Feature update failed');return}setFlags(b.flags||{...flags,[key]:enabled});setStatus(`${features.find(f=>f.key===key)?.name||key} ${enabled?'enabled':'disabled'}.`)}finally{setBusy('')}}
  async function saveOpenAIKey(){const key=apiKey.trim();if(!key){setKeyStatus('Paste an OpenAI API key first.');return}setKeyBusy(true);setKeyStatus('Validating with OpenAI…');try{const r=await fetch('/api/settings/openai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:key})}),b=await r.json().catch(()=>({}));if(!r.ok){setKeyStatus(b.error||'Could not save OpenAI API key');return}setOpenAI({configured:true,last4:b.last4||key.slice(-4),validatedAt:b.validatedAt||new Date().toISOString()});setApiKey('');setKeyStatus(`OpenAI key validated and stored securely ••••${b.last4||key.slice(-4)}`)}finally{setKeyBusy(false)}}
  async function removeOpenAIKey(){setKeyBusy(true);setKeyStatus('Removing OpenAI key…');try{const r=await fetch('/api/settings/openai',{method:'DELETE'}),b=await r.json().catch(()=>({}));if(!r.ok){setKeyStatus(b.error||'Could not remove OpenAI API key');return}setOpenAI({configured:false,last4:null,validatedAt:null});setApiKey('');setKeyStatus('OpenAI key removed. AI features cannot use OpenAI until you add another key.')}finally{setKeyBusy(false)}}
  async function signOut(){const sb=createClient();await sb.auth.signOut();router.replace('/')}
  return <><DashboardNav onSignOut={signOut}/><main className="app-main">
    <section className="dashboard-hero"><div><span className="eyebrow">FEATURE CENTER</span><h1>You decide what CTCI runs.</h1><p>Every optional module is server-side feature gated. A feature only becomes STABLE after an end-to-end or explicit streamer verification is recorded; build/static tests alone keep it BETA.</p></div><div className="hero-status"><div><strong>{Object.values(flags).filter(Boolean).length} enabled</strong><span>{status}</span></div></div></section>

    <section className="panel"><div className="section-head"><div><span className="section-kicker">OPENAI · BRING YOUR OWN KEY</span><h2>Use your own OpenAI API key</h2><p className="muted">Optional. Your key is validated against OpenAI, encrypted by Supabase Vault, and only retrieved server-side for your own AI features. CTCI never returns the saved key to the browser.</p></div></div>
      <div className="setup-grid"><article className={`setup-card ${openAI.configured?'done':''}`}><div className="setup-index">{openAI.configured?'✓':'AI'}</div><div className="setup-copy"><h3>{openAI.configured?'OpenAI connected':'No OpenAI key saved'}</h3><p>{keyStatus}</p>{openAI.validatedAt&&<span className="small muted">Last validated: {new Date(openAI.validatedAt).toLocaleString()}</span>}</div></article></div>
      <div className="field"><label>OpenAI API key</label><input type="password" autoComplete="off" spellCheck={false} value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder={openAI.configured?`Replace key ending in ${openAI.last4||'••••'}`:'Paste your OpenAI API key'}/><span className="small muted">The plaintext key is used only for validation and then stored in Supabase Vault. It is never written to browser storage or returned by this page.</span></div>
      <div className="actions"><button className="btn primary" type="button" disabled={keyBusy||!apiKey.trim()} onClick={()=>void saveOpenAIKey()}>{keyBusy?'Working…':openAI.configured?'Validate & replace key':'Validate & save key'}</button>{openAI.configured&&<button className="btn ghost" type="button" disabled={keyBusy} onClick={()=>void removeOpenAIKey()}>Remove key</button>}</div>
    </section>

    {groups.map(([group,list])=><section className="panel" key={group}><div className="section-head"><div><span className="section-kicker">{group.toUpperCase()}</span><h2>{group}</h2></div></div><div className="setup-grid">{list.map(feature=>{const enabled=flags[feature.key]===true,stable=feature.release==='stable';return <article className={`setup-card ${enabled?'done':''}`} key={feature.key}><div className="setup-index">{stable?'✓':'β'}</div><div className="setup-copy"><div className="actions" style={{gap:8,marginBottom:4}}><h3 style={{margin:0}}>{feature.name}</h3><span className="small" style={{fontWeight:800}}>{stable?'STABLE':'BETA'}</span></div><p>{feature.description}</p><div className="actions" style={{marginTop:8,flexWrap:'wrap'}}>{feature.requirements.map(req=><span className="small muted" key={req}>• {requirementLabel[req]||req}</span>)}<span className="small muted">• {runtimeLabel[feature.maturity]||feature.maturity}</span>{feature.verification?.testedAt&&<span className="small muted">• Last {feature.verification.testKind||'test'}: {new Date(feature.verification.testedAt).toLocaleString()}</span>}{!stable&&<span className="small muted">• Awaiting end-to-end verification</span>}{enabled&&<Link className="btn compact" href={`/dashboard/features/${feature.key}`}>Configure / Test</Link>}</div></div><label className="check"><input type="checkbox" checked={enabled} disabled={busy===feature.key} onChange={e=>void toggle(feature.key,e.target.checked)}/>{enabled?' Enabled':' Disabled'}</label></article>})}</div></section>)}
  </main></>
}
